### ISSUE TITLE
Upgrade single node from chef 12-15 to Effortless

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1016]
#### Job to be Done:

As an IT Operator,

I want to upgrade a single node to effortless

So that I can learn and build trust in the process before expanding to more of my fleet

#### **Description** :

1. Use chef-analyze to identify a node to begin with
    1. This needs to be a node whose run list and attributes are mostly static, so our 'snapshot' for testing does not get out of sync with production.
    1. A node that does not currently use policyfiles
2. Use some new tooling to "suck" that nodes current state into a local testing environment
3. Converge in in kitchen to ensure we are starting from a working state
4. Upgrade chef client and converge to see failures
5. Open VS Code with Chef plugin and start fixing cookstyle violations required to make local node converge on 15:

    1. Loop until successful converge:

          1. Fix issue
          2. Run tests
6. Have user identify policy file and switch things to effortless
7. Test converge
8. Apply to node

#### Scoping:

For this card we limit scope by leaning on PS to cover cultural/process constraints at customers. We focus on a single node where all the policy can be shipped together, not the use cases of multiple teams updating different parts.

We want to find a node with cookbooks that do not depend on external resources (environments, roles, node search, etc.) that do not work in the Effortless pattern.

#### Open Questions:

1. Does this impact licensing? Moving from old chef node license to new infra offering.
1. If a customer is using external resources (EG, Chef environments, clustered services, search) how do we support those in the Effortless pattern?

#### **Acceptance Criteria:**

1. Chef Workstation ships tooling that allows customers to inspect their fleet and select nodes/cookbooks to upgrade.

    1. `chef analyze report nodes/cookbooks`
    2. `chef analyze report node <name>/cookbook name`
    3. chef analyze tool provides hints/suggestions of first node to start with
2. Chef Workstation Team provides documentation of upgrades paths clearly indicating which parts are automated/assisted and which parts require human tasks/decisions.
3. Chef Workstation ships tooling that guides the customer through the upgrade and migration workflow for a single node.

Aha! Link: https://chef.aha.io/features/SH-24

**Comment by tyler-ball** [comment]
Now that we have a capture command ready for user consumption, we face the problem of "what happens if my clone tries to write information into production?"

**Comment by tyler-ball** [comment]
Somethings users have requested:

1. For the supermarket cookbook pattern, can Upgrade Lab show me:
  a) any cookbooks with newer versions on the supermarket
  b) if any of them are deprecated
  c) show me a diff?
  d) help me grab a newer copy?
1. Do I have orphaned cookbooks? 
1. Any that aren't in any nodes expanded run list?
1. Can I delete them from my cookbook repo and make it more approachable? (xml and imagemagick appear to be old deps on my system)

**Comment by tyler-ball** [comment]
Closing this since we accomplished and released what we wanted (Upgrade Lab)
