### ISSUE TITLE
Documentation for single node upgrade (Part 1)

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1019]

**Comment by jonsmorrow** [comment]
#### Story
As an Chef PS employee
I want documentation covering the suggest upgrade path using workstation tools
So that I can help my customers migrate to effortless

#### Description
We know some steps in the migration path will require human steps/decisions. This card is about creating a document that PS can follow to guide the upgrade. It should be clear about what things the tool helps with and what parts require human steps.

#### Acceptance Criteria
1. Document exists
2. Following the doc results in a working effortless package deployed to the node

**Comment by tyler-ball** [comment]
Additional suggestions from my research :
  * Need capability / instructions for how to target a specific Chef version in Cookstyle
  * `chef-analyze` only runs a subset of Cookstyle rules, we need to communicate that to users

**Comment by clintoncwolfe** [comment]
Version 1 here:
https://docs.google.com/document/d/1T8-L7W2SUA1Mhh7PGWXh4As1XwvfwUvNqrPkXG_RJSc/edit?ts=5e838cf0#
