### ISSUE TITLE
chef <analyze> capture node <name> (Follow dep chain)

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1022]

**Comment by jonsmorrow** [comment]
#### Story
As an IT Operator
I want to capture the current state of a node into a local kitchen
So that I can begin testing changes

#### Description
This story is the second pass of creating a local kitchen environment. Getting the code form the node cache while efficient doesn't get us to the source. This story is about following the dependency chain to all the bits for the run from there source location.

#### Questions
1. Can we suggest a similar platform or ask for an image (docs/PS could help get one)

#### Acceptance Criteria
1. Command exists to capture current state
2. User can run kitchen converge with the version of chef on a similar platform to the current node

**Comment by tyler-ball** [comment]
Some other suggestions I found from my research:
* Visualize the cookbook dependency tree for users
* Identify open source cookbooks for users
* Identify when open source cookbooks are out of date, and how many cookstyle violations could be fixed by upgrading

**Comment by tyler-ball** [comment]
Notes from planning discussion: if we are going to be gathering cookbook sources, I think we should do that in the scope of a Policyfile.

The previous cards [1](https://github.com/chef/chef-workstation/issues/1018) [2](https://github.com/chef/chef-workstation/issues/1017) do not require knowing the cookbook source. But as soon as users want to start fixing issues in cookbooks, they need to perform those fixes in the real source.

I propose that a first step for introducing a policyfile would be to introduce it with a `default_source :chef_repo, "../"` that points to the local repo they have established using the previous cards. As they identify cookbooks they need to fix, they can switch their policyfile to point to local SCM copies of those cookbooks. Test kitchen knows how to generate a policyfile lock, so as users fix issues in the cookbooks and those changes flow through their pipeline, their local kitchen tests continue to mirror their production instances.
