### ISSUE TITLE
Update Workstation to Ruby 2.7 for Chef Infra Client

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1045]
### Describe the Enhancement:
Chef Infra Client 16 is now running on Ruby 2.7 in the current channel per our yearly Ruby version bumping schedule. This release will ship in the 2nd half of April and requires that Chef Workstation also ship with a matching Ruby release so we ensure we are bug for bug compatible between the two packages. The Chef Infra Client release in Workstation will need to be increased to 16 along with the release of Ruby used in Workstation.

**Comment by jonsmorrow** [comment]
We will write a story for the next sprint to capture this work.

**Comment by tyler-ball** [comment]
Released in 20.6
