### ISSUE TITLE
Clean/merge obsolete www docs

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation#1047]
Assist releng team in merging chef.sh docs into the main doc site. 
A PR is open: https://github.com/chef/chef-workstation/pull/1037

The intent is to update (in the PR above) the www/ docs 
* merge orphaned content into existing pages
* add menu entries for orphaned content that should  be present
* delete orphaned content that is no longer applicable. 

To identify the orphaned content, deploy the docs locally (instructions in www/) and visit localhost:1313/.  Anything identified as "Missing" needs to have one of the actions above applied.

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-workstation/pull/1037
