### ISSUE TITLE
WS Windows 10 Testing

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1051]
#### Job to be Done:

As an engineering team,

We want to test WS on Windows 10

So that we ensure our produt works on modern windows and supports the desktop offering

#### 

#### Description:

The Releng team is adding Windows 10 pipelines in build kite. We need to ensure Workstation can be built and passes tests on this platform once these pipelines are available. Additionally we need to ensure we have minimal testing around the infra client we ship to support the desktop offering.

#### Acceptance Criteria:

1. Workstation package for Windows 10 exists
2. Workstation Windows 10 package can be used to enroll in desktop manager offering.

Aha! Link: https://chef.aha.io/features/SH-54

**Comment by tas50** [comment]
This was done
