### ISSUE TITLE
Chef Workstation April Major Version Release

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1059]
### Describe the Need:

* Chef Workstation major version
  - [x] Work with Belfast team on getting a card to release the standalone InSpec package updated with Ruby 2.7
  - [ ] Work with marketing on announcement messaging. What channels does this need to go to besides discourse?
  - [ ] Check kitchen-\* and knife-\* plugins for Ruby 2.7 deprecation warnings
  - [x] Chef Infra Client 16
  - [ ] Check for duplicates of any gems
  - [x] Push jobs client https://github.com/chef/opscode-pushy-client/pull/205
  - [x] Pull in Ruby 2.7 #1123
    - [x] Remove Rubygems/Bundler omnibus software deps because Ruby already includes these (confirm with Tim)
    - [x] https://github.com/chef/customer-bugs/issues/160 - update Rake >= 13
  - [x] Release Inspec which includes support for Ruby 2.7
  - [x] Switch to date based versioning scheme #1112
    * Proposal `2020.04.03120000` - still fits the Rubygems semver definition for our rubygems and conveys dates
    * This does not work on Windows, needs to be `20.4.100` (last 2 of year, non-padded month, build number)
    * Ensure this scheme works with Expeditor, Artifactory, and omnitruck
  - [x] Cookstyle major version bump
    * ~Remove Foodcritic~ Leaving it in
    * Link to Cookstyle docs and blog post as part of release announcement
  - [x] Windows 10 support
  - [x] Include bcrypt-pbkdf 1.1.0 after that is released (ensures new format ssh keys can be used), remove custom omnibus definition
  - [x] Update git - https://lkml.org/lkml/2020/4/20/1252 https://github.com/chef/omnibus-software/pull/1189, #1124
  - [x] ~Our habitat distributions of packages need to be updated to depend on ruby 2.7 - there is a version-named package on Linux but not Windows, although there is a PR for that.~ We don't currently build Chef Workstation for a habitat distribution
  - [x] yml as valid recipe extension, https://github.com/chef/chef-cli/pull/63
    - [x] Test `chef-run` support for yml recipes
  - [x] Fix Docker API build issues
  - [x] Berkshelf 7.0.10
  - [x] Chef Workstation App customer issue
  - [x] Refresh Chef Workstation App dependencies, nodejs
* ChefDK 4
  - [x] Chef 15.10.12 for ChefDK 4, validate train update (https://github.com/chef/chef/pull/9635)
  - [x] https://github.com/chef/customer-bugs/issues/160 - update Rake >= 13
  - [x] Ruby 2.6.6 for CVEs
  - [ ] Announce EOL date for ChefDK
  - [ ] Schedule follow up for EOL and boneyarding ChefDK
  - [ ] Check for duplicates of any gems
* ChefDK 3
  - [ ] Chef 14.15.6
  - [ ] ~? Pull download links~ Will be decided by marketing
  - [ ] Check for duplicates of any gems
  - [ ] Remove ChefDK 3 pipeline from expeditor config
- [ ] Update https://docs.chef.io/versions/ to the latest information for ChefDK and Chef Workstation (ChefDK 3 is EOL, ChefDK 4 is deprecated

**Comment by jonsmorrow** [comment]
We need to remove foodcritic as part of this.

**Comment by tyler-ball** [comment]
Release ChefDK 3/4 and Workstation to address CVEs - https://github.com/chef/omnibus-software/pull/1176

**Comment by pschaumburg** [comment]
Can we also add version updates to the following gems?
- inspec
- kitchen-inspec
- kitchen-vcenter

**Comment by tyler-ball** [comment]
@pschaumburg Yup! Its not explicitly called out, but we'll be updating all the available deps as part of this. If you are ready to consume that the current channel already has a release that includes updates to those (`20.4.6`)
