### ISSUE TITLE
Update Chocolatey

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1065]
#### Job To Be Done
As an operator,
I want to install Chef products using Chocolatey
So that I can take advantage of their package management capabilities

#### Description
Both our homebrew and chocolatey definitions are out of date. We should probably get these updated. We working on an effort to rework our download flow. This card is 4 fold:
1. We should discuss this with product. We want to make sure this is still a supported install path and if so that we do it in a way that ensures metrics for download.
2. Update the software definitions in Chocolatey
3. Look at pipeline so these stay up-to-date

#### Acceptance Criteria
* [X] Decision made on support and interaction with the new downloads work [Yes]
* [x] Latest package is installed via `choco install chef-workstation`
* [x] Definitions are updated when a new package is promoted
* [ ] Ensure the latest version of ChefDK 3 and 4 are pushed to the chocolatey repo

Notes:
We need to figure out how to count the number of downloads initiated through these methods. Probably not work for our team but this convo and work needs to happen.

**Comment by btm** [comment]
automating chocolatey:

We recently created a central chocolatey account `chef-ci` in https://github.com/chef/release-engineering/issues/1139. @tas50 is going to get that account added to all of our packages.

Should be straightforward to:
- put the chocolatey API key in an environment variable in [expeditor](https://github.com/habitat-sh/habitat/blob/master/.expeditor/finish_release.pipeline.yml#L31)
- copy the [publish_to_chocolatey.ps1](https://github.com/habitat-sh/habitat/blob/master/.expeditor/scripts/finish_release/publish_to_chocolatey.ps1) from habitat
- replace the package code there with a direct link to https://packages.chef.io/files/stable/chef-workstation/VERSION/windows/2019/chef-workstation-VERSION-x64.msi
- copy the project directory from chef/chocolatey-packages into the project

Then run the script by hand for the versions we've missed to verify, and leave it in place to automatically create future stable releases. Ideally this all happens without a PR so we don't have to remember to do it like with https://github.com/chef/homebrew-chef/ right now.

**Comment by marcparadise** [comment]
Pipeline changes/auto-publish is complete with chef/chef-workstation#1114.
The latest DK 4 is published to choco. 

The latest DK 3 is not.  I have created the package, but do not have the API key (outside of usage in CI, but this is a one-off and isn't via the build pipeline)

**Comment by marcparadise** [comment]
Published DK 3.13.1 (last DK3 release) to chocolatey today.
