### ISSUE TITLE
Implement `dist` for executables in workstation

### ISSUE THREAD

**Issue by tarcinil** [chef/chef-workstation#1086]
### Describe the Need:
As part of building out Cinc Workstation, we need to be able to overload `chef-` so that we are trademark compliant.

### Can We Help You Implement This?:

N/A - I have a good idea of the actions that I need to perform

1. Update https://github.com/chef/chef-workstation/blob/master/components/main-chef-wrapper/main.go#L46
2. Update https://github.com/chef/chef-workstation/blob/master/components/main-chef-wrapper/main.go#L75
3. make sure that omnibus can change the entrypoint CLI

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-workstation/pull/1087 - Thank you @tarcinil
