### ISSUE TITLE
Update Homebrew

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation#1094]
#### Job To Be Done
As an operator,
I want to install Chef products using Homebrew
So that I can take advantage of their package management capabilities

#### Description
Our homebrew definition is out of date. We should probably get this updated. We working on an effort to rework our download flow. This card is 3 fold:
1. We should discuss this with product. We want to make sure this is still a supported install path and if so that we do it in a way that ensures metrics for download.
2. Update the software definitions in homebrew
3. Look at pipeline so these stay up-to-date

#### Acceptance Criteria
* [X] Decision made on support and interaction with the new downloads work [Yes]
* [ ] Latest package is installed via `brew install chef-workstation`
* [ ] workstation is maintained in homebrew , since it now meets the criteria for a desktop application
* [ ] Remove Workstation definition from `chef/homebrew-chef` and disable expeditor from updating this
* [ ] Definitions are updated when a new package is promoted

Notes:

We need to figure out how to count the number of downloads initiated through these methods. Probably not work for our team but this convo and work needs to happen.

**Comment by tyler-ball** [comment]
Historic context: https://github.com/Homebrew/homebrew-cask/pull/47905

**Comment by tyler-ball** [comment]
We're waiting on https://github.com/Homebrew/homebrew-cask/pull/81618 to merge. We also need to add the scripts into our third-party pipeline to create that cask PR:
1) Checkout master of https://github.com/chef/homebrew-cask
2) Reset that to HEAD of the upstream
3) Make a branch for our incoming commit
4) Make a commit with the latest version of Chef Workstation
5) Open a PR against the upstream using their form body

**Comment by tyler-ball** [comment]
Done!
