### ISSUE TITLE
Convert Upgrade Labs Document to Markdown

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/chef-workstation#1121]
## Description
Convert the Upgrade Labs Document to Markdown

Related to #1019

## Acceptance Criteria
1. The Upgrade Labs document exists in Markdown format in the chef/chef-web-docs repo.
1. The original Google doc is locked against further edits but may accept comments.
1. A note is added to the original google doc directing viewers to the new location.

**Comment by tyler-ball** [comment]
Merged!
