### ISSUE TITLE
Upgrade Lab test environment

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1133]
### Describe the Enhancement:
One of our ChefConf deliverables is an upgrade guide to walk customers through upgrading their cookbooks to support Chef Infra Client 16. For them to be able to test this we need to create a test environment they can utilize.

### Describe the Need:
* Test environment can be created and destroyed at will
* Environment setup:
  * Chef Server 12.4 with multiple cookbooks that have non-infra-16-compliant issues
  * Chef Server 13.x (latest) that is blank
  * 1 nodes with Chef Infra 12.x (latest) installed and bootstrapped to Chef Server with 12 installed
  * Bootstrapping should converge nodes so we have information in the server on these nodes
* Documentation is provided on how to create and destroy the environment
* After environment is created, tooling outputs all information user needs to access the environment
  * EG, hostnames, certificate locations, etc.

**Comment by tyler-ball** [comment]
The Chef Workstation team will be responsible for spinning up and down these environments and getting access for teams who need access (docs, training, etc.)

**Comment by tyler-ball** [comment]
Next step: we want someone else to try and spin up a test environment and find issues we need to address before merging this.

Next next step: run the Upgrade Labs doc against this environment and address potential improvements.

**Comment by clintoncwolfe** [comment]
The repo for the test environment build scripts is at https://github.com/chef/upgrade-lab-demo-env

**Comment by tyler-ball** [comment]
Great job @clintoncwolfe !
