### ISSUE TITLE
Bump kitchen-azurerm to 0.17.0

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef/chef-workstation#1138]
### Describe the Enhancement:
This specific gem version is critical for security-conscious Azure users as it will support a more secure authentication method for Test Kitchen & Azure

### Describe the Need:
Security-conscious users that build with kitchen-azurerm need a more secure auth method for TK & Azure

### Current Alternative
Current alternative is to manually bump the gem inside of Workstation

### Can We Help You Implement This?:
If this is a simple version bump in the gemfile, I'm happy to PR it. If it requires more than that, I'll defer to the team.

**Comment by tyler-ball** [comment]
Updated in master, will go out in next release within the week (the major version release, `20.x`)

**Comment by OBrienCommaJosh** [comment]
🤘 Thanks!
