### ISSUE TITLE
[TRACKER]Chef Workstation 2020 Testing - Knife Windows

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef-workstation#1180]
## Description
- Setup chef-workstation on your system per https://github.com/chef/chef-workstation/issues/1167#issuecomment-627407517
- Verify functionality and leave a comment for the results of the command
## Parent task
https://github.com/chef/chef-workstation/issues/1167
## Reference
https://github.com/chef/knife-windows/

**Comment by sanga1794** [comment]
I was executing `knife wsman test IP -m`, got below exception

```
Exception: NameError: uninitialized constant Chef::Knife::WinrmSession
Did you mean?  Chef::Knife::WinrmBase
```

**Comment by sanga1794** [comment]
```
knife windows cert generate -H "hostname" 
Enter certificate passphrase (empty for no passphrase):
Generated Certificates:
- winrmcert.pfx - PKCS12 format key pair. Contains public and private keys, can be used with an SSL server.
- winrmcert.b64 - Base64 encoded PKCS12 key pair. Contains public and private keys, used by some cloud provider API's to configure SSL servers.
- winrmcert.pem - Base64 encoded public certificate only. Required by the client to connect to the server.
Certificate Thumbprint: 38C71880E9EEAEA199556AA883AD1514586829E2

```

**Comment by sanga1794** [comment]
```
knife winrm -w ssl "role:web" "net stats srv" -x Adminstrator -P 'password'
FATAL: No nodes returned from search!
```

**Comment by btm** [comment]
https://github.com/chef/knife-windows/pull/500 is in knife-windows 3.0.17, which is in chef-workstation 20.5.41, which is currently building and should be available for further testing in 2 hours.

**Comment by sanga1794** [comment]
` knife windows cert install ".\server_cert.pfx" --cert-passphrase "strong_passphrase"`
`Adding certificate to the Windows Certificate Store...
Certificate added to Certificate Store`

**Comment by sanga1794** [comment]
`knife windows listener create --cert-passphrase "strong_passphrase" --hostname "sanga-windows" --cert-install ".\server_cert.pfx"
Certificate installed to Certificate Store
Certificate Thumbprint: THUMBPRINT
WinRM listener created with Port: 5986 and CertificateThumbprint: THUMBPRINT`

**Comment by dheerajd-msys** [comment]
Thank you working on this @sanga1794 . Looks good.

**Comment by btm** [comment]
@dheerajd-msys https://github.com/chef/chef-workstation/issues/1180#issuecomment-629016336

That looks like a bug.

The knife winrm test above wasn't really a complete one, but I tried it OK:
```
$ /opt/chef-workstation/bin/knife winrm -m ip.ip.ip.ip hostname -x btm -P PASSWORD
ip.ip.ip.ip btm-win10
ip.ip.ip.ip
$ 
```

**Comment by dheerajd-msys** [comment]
@btm https://github.com/chef/chef-workstation/issues/1180#issuecomment-629016336  is fixed in https://github.com/chef/knife-windows/pull/500
Is there anything else do you want us to test and fix to keep this open?

Thanks!!

**Comment by btm** [comment]
@dheerajd-msys Can you put the version of the first build in current of workstation that contains the fixed version of knife-windows here, then close this?

**Comment by dheerajd-msys** [comment]
Sure @btm, chef-workstation build `20.5.44` from current https://downloads.chef.io/chef-workstation/current had the fix https://github.com/chef/knife-windows/pull/500
