### ISSUE TITLE
[TRACKER]Chef Workstation 2020 Testing - Knife Vsphere

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef-workstation#1186]
## Description
- Setup chef-workstation on your system per https://github.com/chef/chef-workstation/issues/1167#issuecomment-627407517
- Verify functionality and leave a comment for the results of the command
## Parent task
https://github.com/chef/chef-workstation/issues/1167
## Reference
https://github.com/chef/knife-vsphere
## Chef Workstation Version
```
chef -v

Chef Workstation version: 20.6.62
Chef Infra Client version: 16.1.16
Chef InSpec version: 4.19.0
Chef CLI version: 3.0.4
Test Kitchen version: 2.5.1
Cookstyle version: 6.7.3
```

**Comment by sanga1794** [comment]
` knife vsphere template list -VV  -c Desktop//stove/.chef/knife.rb
 
INFO: Using configuration from /home/Sangamesh/Desktop/stove/.chef/knife.rb
DEBUG: value for config item vsphere_host: vcenter.success.chef.co
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: amol@success.chef.co
DEBUG: value for config item vsphere_pass: Success1!
DEBUG: value for config item vsphere_pass: Success1!
DEBUG: value for config item vsphere_pass: Success1!
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
DEBUG: value for config item folder: 
DEBUG: value for config item vsphere_dc: Tierpoint
Template Name: amol-test-windows

Template Name: amol-test

Template Name: ubuntu1804-template-old

Template Name: windows2016-template

Template Name: windows2016-template-old

Template Name: ubuntu1804-template

Template Name: centos80-template

Template Name: centos76-template

Template Name: esxi65-template

Template Name: centos77-template`

**Comment by sanga1794** [comment]
`knife vsphere pool list -c Desktop/stove/.chef/knife.rb `
Pool: devcluster/packer
Pool: devcluster/test-kitchen
Pool: devcluster/Core Infra
Pool: devcluster/a2-ha-backend

**Comment by sanga1794** [comment]
`knife vsphere folder list -c Desktop/stove/.chef/knife.rb`
Folder: vm
   Folder: Dev for CIS Profiles
   Folder: Jason-Vms
   Folder: VRM
   Folder: Irving
   Folder: Templates
   Folder: Discovered virtual machine
   Folder: Amol-VMs
   Folder: Core Infra don't mess with

**Comment by sanga1794** [comment]
`knife vsphere cpu ratio -c Desktop/stove/.chef/knife.rb`
`### Cluster devcluster ###
172.31.7.102: 0.6666666666666666
172.31.7.101: 1.0
172.31.7.100: 1.5416666666666667`

**Comment by sanga1794** [comment]
`knife vsphere datastore list -c Desktop/stove/.chef/knife.rb`
Datastores:
  Capacity:  550.75 GB
  Datastore: datastore3
  Free:      144.76 GB
  
  Capacity:  4.09 TB
  Datastore: vsanDatastore
  Free:      3.09 TB
  
  Capacity:  550.75 GB
  Datastore: datastore1
  Free:      393.31 GB
  
  Capacity:  550.75 GB
  Datastore: datastore2
  Free:      156.58 GB
Pool:       devcluster

**Comment by sanga1794** [comment]
`knife vsphere datastore maxfree -c Desktop/stove/.chef/knife.rb`
Datastore: vsanDatastore

**Comment by sanga1794** [comment]
`knife vsphere vm list -c Desktop/stove/.chef/knife.rb`
Folder: 
	VM Name: ubuntutest
		IP: 
		RAM: 2048
		State: off
	VM Name: win-test-2
		IP: 
		RAM: 4096
		State: off
	VM Name: a2-ha-backend provisioning node
		IP: 
		RAM: 2048
		State: suspended
	VM Name: migration-chef-server
		IP: 
		RAM: 4096
		State: suspended
	VM Name: windows-admin
		IP: 
		RAM: 8192
		State: off
	VM Name: A2_bcc320e9_backend_elasticsearch_03
		IP: 172.31.11.46
		RAM: 8192
		State: on
	VM Name: A2_bcc320e9_backend_elasticsearch_02
		IP: 172.31.11.11
		RAM: 8192
		State: on
	VM Name: A2_bcc320e9_backend_elasticsearch_01
		IP: 172.31.11.36
		RAM: 8192
		State: on
	VM Name: amol-test1
		IP: 
		RAM: 2048
		State: off

**Comment by sanga1794** [comment]
`knife vsphere vm delete Vsphereubuntu`
Deleted virtual machine Vsphereubuntu

**Comment by sanga1794** [comment]
`knife vsphere vm clone Vsphereubuntu --template ubuntu1804-template-old`
Cloning template ubuntu1804-template-old to new VM Vsphereubuntu
Finished creating virtual machine Vsphereubuntu

**Comment by sanga1794** [comment]
`knife vsphere vm find --match-name ubuntutest`
name:  ubuntutest
state: off

**Comment by sanga1794** [comment]
`knife vsphere vm find --power-off`
name:  esxi65-template
state: off

name:  cis-esx67.dev01.success.chef.co
state: off

name:  amol-test
state: off

name:  amol-test-windows
state: off

name:  win-test-2
state: off

name:  amol-test1
state: off

name:  amol-test-windows-1
state: off

name:  amol-test34
state: off

name:  windows2016-template-old
state: off

name:  windows-admin
state: off

name:  centos76-template
state: off

name:  ubuntutest
state: off

name:  ubuntu1804-template
state: off

name:  windows2016-template
state: off

name:  centos77-template
state: off

name:  ubuntu1804-template-old
state: off

name:  centos80-template
state: off

name:  cis-vcenter-65-sbox01.success.chef.co
state: off

name:  ubs-cis-esxi.success.co
state: off

**Comment by sanga1794** [comment]
`knife vsphere vm state ubuntutest -s on`
Powered on virtual machine ubuntutest

**Comment by sanga1794** [comment]
`knife vsphere vm state ubuntutest -s reboot`
Reboot virtual machine ubuntutest

**Comment by sanga1794** [comment]
`knife vsphere vm state ubuntutest -s off`
Powered off virtual machine ubuntutest

**Comment by sanga1794** [comment]
`knife vsphere vm list -c Desktop/stove/.chef/knife.rb --recursive`
Folder: 
	VM Name: ubuntutest
		IP: 
		RAM: 2048
		State: off
	VM Name: win-test-2
		IP: 
		RAM: 4096
		State: off
	VM Name: a2-ha-backend provisioning node
		IP: 
		RAM: 2048
		State: suspended

**Comment by sanga1794** [comment]
`knife vsphere vm find -c Desktop/stove/.chef/knife.rb  --alarms --cpu  --cpu-hot-add-enabled  --esx-di--full-path  --short-path`
alarms:              green
cpu:                 4
cpu_hot_add_enabled: false
esx_disk:
  [vsanDatastore] 7c75c55e-da88-4f53-da0f-002219654bd9/esxi65-template.vmdk
folder:              Templates
name:                esxi65-template
state:               off

alarms:              green
cpu:                 4
cpu_hot_add_enabled: false
esx_disk:
  [vsanDatastore] da3abf5e-89f7-1d18-6d1b-00221967b1fa/cis-esx65-dev01.success.chef.co.vmdk
folder:              Dev for CIS Profiles
name:                cis-esx65-dev01.success.chef.co
state:               on

alarms:              green
cpu:                 2
cpu_hot_add_enabled: false
esx_disk:
  [vsanDatastore] 37d9855e-a8fd-0a4a-2345-00221967b1fa/ubuntutest.vmdk
folder:              vm
name:                ubuntutest
state:               off

alarms:              green
cpu:                 4
cpu_hot_add_enabled: false
esx_disk:
  [vsanDatastore] 9520bf5e-4d3a-a240-5604-002219654bd9/cis-esx67.dev01.success.chef.co.vmdk
folder:              Dev for CIS Profiles
name:                cis-esx67.dev01.success.chef.co
state:               off

**Comment by sanga1794** [comment]
`knife vsphere vm state ubuntutest -c Desktop/stove/.chef/knife.rb --recursive`
VM ubuntutest is currently powered off

**Comment by sanga1794** [comment]
`knife vsphere vm show ubuntutest config.hardware.memoryMB config.hardware.numCPU -F json -c Desktop/stove/.chef/knife.rb`
[
  {
    "config.hardware.memoryMB": 2048
  },
  {
    "config.hardware.numCPU": 2
  }
]

**Comment by sanga1794** [comment]
`knife vsphere hosts list -c Desktop/stove/.chef/knife.rb `
Hosts:
  Host: IP1
  
  Host: IP2
  
  Host: IP3
Pool:  devcluster

**Comment by sanga1794** [comment]
`knife vsphere hosts list -c Desktop/stove/.chef/knife.rb  --pool devcluster`
Hosts:
  Host: IP1
  
  Host: IP2
  
  Host: IP3
Pool:  devcluster

**Comment by sanga1794** [comment]
`knife vsphere template list -VV  -c Desktop//stove/.chef/knife.rb`
Template Name: amol-test-windows

Template Name: amol-test

Template Name: ubuntu1804-template-old

Template Name: windows2016-template

Template Name: windows2016-template-old

Template Name: ubuntu1804-template

Template Name: centos80-template

Template Name: centos76-template

Template Name: esxi65-template

Template Name: centos77-template

**Comment by sanga1794** [comment]
`knife vsphere vm find --alarms --cpu --cpu-hot-add-enabled --esx-disk --full-path --short-path --hostname  --host_name --ip --networks --os --os-disk --ram --memory-hot-add-enabled  --snapshots  --tools -c Desktop/stove/.chef/knife.rb`
alarms:                 green
cpu:                    4
cpu_hot_add_enabled:    false
disks:
esx_disk:
  [vsanDatastore] 7c75c55e-da88-4f53-da0f-002219654bd9/esxi65-template.vmdk
folder:                 Templates
host_name:              HOST IP
hostname:               
ip:                     
memory_hot_add_enabled: false
name:                   esxi65-template
networks:
os:                     
ram:                    16384
snapshots:
state:                  off
tools:                  toolsNotRunning

alarms:                 green
cpu:                    4
cpu_hot_add_enabled:    false
disks:
esx_disk:
  [vsanDatastore] da3abf5e-89f7-1d18-6d1b-00221967b1fa/cis-esx65-dev01.success.chef.co.vmdk
folder:                 Dev for CIS Profiles
host_name:              HOST IP
hostname:               localhost
ip:                     IP
memory_hot_add_enabled: false
name:                   name
networks:
  ip:     IP
  name:   VM Network
  prefix: 20
os:                     VMware ESXi 6.5 or later
ram:                    4096
snapshots:
state:                  on
tools:                  toolsOk

**Comment by dheerajd-msys** [comment]
Everything looks good, This is all tested on Chef Workstation version: 20.6.62
