### ISSUE TITLE
Remove chef-telemetry dependency on external http gem

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1200]
### Describe the Enhancement:
chef-telemetry is a low level library that we plan on implementing across all our Ruby based products. As such, we want to ensure it has as few external dependencies as possible.

When it was first written it included the [http](https://github.com/httprb/http) gem which had a small number of dependencies. Now that gem, at version 4.x, has an external dependency on a native extension.

### Acceptance criteria
* Rewrite the functionality in chef-telemetry to use built in standard http libraries
* Remove http gem dependency
* Revert https://github.com/chef/chef-workstation/commit/59fe0a676fcdef2ce094d49e48cfd496a2895f66#diff-68fc8abe25ae7c3184ef8188cf21cddd . We needed to do this because the http gem native extension ended up there. No other gem with native extensions seems affected.  
* Update chef-run, chef-workstation, Inspec, and any other gems that depend on chef-telemetry to use the new version which does not require the http gem. Get a current channel build of chef-workstation and ensure it does not contain the http gem.

**Comment by clintoncwolfe** [comment]
Re-opening until all the deps are updated

**Comment by clintoncwolfe** [comment]
Updated chef-telemetry gem is v1.0.8 on rubygems
