### ISSUE TITLE
[TRACKER]Chef Workstation 2020 Testing - Knife Push

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef-workstation#1214]
## Description
- Setup chef-workstation on your system per https://github.com/chef/chef-workstation/issues/1167#issuecomment-627407517
- Verify functionality and leave a comment for the results of the command
## Parent task
https://github.com/chef/chef-workstation/issues/1167
## Reference
https://github.com/chef/knife-push
https://docs.chef.io/ctl_chef_server/#install
https://docs.chef.io/push_jobs/

**Comment by antima-gupta** [comment]
>knife node status node-push-job
node-push-job available

>knife job start 'chef-client -r recipe[git]' node-push-job

Started.  Job ID: a2b87f87052d213c0703eadb21bdf20e
.Quorum_failed.
command:     chef-client -r recipe[git]
created_at:  Thu, 21 May 2020 13:14:32 GMT
env:
id:          a2b87f87052d213c0703eadb21bdf20e
nodes:
  nacked: node-push-job
run_timeout: 3600
status:      quorum_failed
updated_at:  Thu, 21 May 2020 13:14:32 GMT

>knife job start 'my_script.sh' node-push-job
Started.  Job ID: a2b87f87052d40e1ca44e6f89a9c97df
.Quorum_failed.
command:     my_script.sh
created_at:  Thu, 21 May 2020 13:21:48 GMT
env:
id:          a2b87f87052d40e1ca44e6f89a9c97df
nodes:
  nacked: node-push-job
run_timeout: 3600
status:      quorum_failed
updated_at:  Thu, 21 May 2020 13:21:48 GMT

>knife job list
command:     chef-client -r recipe[git]
created_at:  Thu, 21 May 2020 13:14:32 GMT
env:
id:          a2b87f87052d213c0703eadb21bdf20e
run_timeout: 3600
status:      quorum_failed
updated_at:  Thu, 21 May 2020 13:14:32 GMT

command:     my_script.sh
created_at:  Thu, 21 May 2020 13:21:48 GMT
env:
id:          a2b87f87052d40e1ca44e6f89a9c97df
run_timeout: 3600
status:      quorum_failed
updated_at:  Thu, 21 May 2020 13:21:48 GMT

**Comment by antima-gupta** [comment]
>knife job start --timeout 10 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052d8d0b2244b0302a8484e6
    .Quorum_failed.
    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:29:02 GMT
    env:
    id:          a2b87f87052d8d0b2244b0302a8484e6
    nodes:
      nacked: node-push-job
    run_timeout: 10
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:29:03 GMT


>knife job start --timeout 10 -q 100% 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052df522c3901a799290dfed
    .Quorum_failed.
    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:30:55 GMT
    env:
    id:          a2b87f87052df522c3901a799290dfed
    nodes:
      nacked: node-push-job
    run_timeout: 10
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:30:55 GMT


>knife job start -q 100% 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052db31d7824a30f11505c55
    .Quorum_failed.
    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:32:01 GMT
    env:
    id:          a2b87f87052db31d7824a30f11505c55
    nodes:
      nacked: node-push-job
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:32:01 GMT

> knife job start -b 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052d522ad93f478035bee041
    /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-push-1.1.5/lib/chef/knife/job_start.rb:116: warning: constant Net::HTTPServerException is deprecated

>knife job start --nowait 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052d42f71fd13b8032a7b054
    /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-push-1.1.5/lib/chef/knife/job_start.rb:116: warning: constant Net::HTTPServerException is deprecated


>knife job start --with-env '{"test": "foo"}' 'list_files_script.sh' node-push-job
    Started.  Job ID: a2b87f87052d425d844807b50771d734
    .Quorum_failed.
    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:43:13 GMT
    env:
      test: foo
    id:          a2b87f87052d425d844807b50771d734
    nodes:
      nacked: node-push-job
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:43:13 GMT


>knife job start --in-dir /home 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052de6f5441df55e3d618abf
    .Quorum_failed.
    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:38:51 GMT
    dir:         /home
    env:
    id:          a2b87f87052de6f5441df55e3d618abf
    nodes:
      nacked: node-push-job
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:38:52 GMT


>knife job start --file abc.json 'list_files_script.sh' node-push-job 
    Started.  Job ID: a2b87f87052d2bf179809add21efac1d
    .Quorum_failed.
    command:        list_files_script.sh
    created_at:     Fri, 22 May 2020 03:40:34 GMT
    env:
    file_specified: true
    id:             a2b87f87052d2bf179809add21efac1d
    nodes:
      nacked: node-push-job
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 03:40:34 GMT

>knife job start --quorum 80% --capture 'chef-client' node-push-job
    Started.  Job ID: a2b87f87052d3ad55eff906e1c0225de
    .Running (1/1 in progress) ...
    ..Complete.
    capture_output: true
    command:        chef-client
    created_at:     Fri, 22 May 2020 06:48:28 GMT
    env:
    id:             a2b87f87052d3ad55eff906e1c0225de
    nodes:
      succeeded: node-push-job
    run_timeout:    3600
    status:         complete
    updated_at:     Fri, 22 May 2020 06:48:46 GMT


>knife job start --quorum 80% 'chef-client' node-push-job
    Started.  Job ID: a2b87f87052d042dbd3b90f23b02e832
    .Running (1/1 in progress) ...
    ...Complete.
    command:     chef-client
    created_at:  Fri, 22 May 2020 06:42:42 GMT
    env:
    id:          a2b87f87052d042dbd3b90f23b02e832
    nodes:
      succeeded: node-push-job
    run_timeout: 3600
    status:      complete
    updated_at:  Fri, 22 May 2020 06:43:15 GMT


>knife job status a2b87f87052db42c167a05b4df53c486
    capture_output: true
    command:        ls
    created_at:     Fri, 22 May 2020 06:27:19 GMT
    env:
    id:             a2b87f87052db42c167a05b4df53c486
    nodes:
      nacked: node-push-job
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 06:27:20 GMT

>knife job output a2b87f87052d3ad55eff906e1c0225de  node-push-job
    Starting Chef Infra Client, version 16.1.0
    resolving cookbooks for run list: ["git"]
    Synchronizing Cookbooks:
      - git (10.0.0)
    Installing Cookbook Gems:
    Compiling Cookbooks...
    Converging 1 resources
    Recipe: git::package
      * git_client[default] action install
        * apt_package[default :create git] action install (up to date)
         (up to date)

    Running handlers:
    Running handlers complete
    Chef Infra Client finished, 0/2 resources updated in 10 seconds


> knife job output a2b87f87052d3ad55eff906e1c0225de --channel stdout node-push-job
    Starting Chef Infra Client, version 16.1.0
    resolving cookbooks for run list: ["git"]
    Synchronizing Cookbooks:
      - git (10.0.0)
    Installing Cookbook Gems:
    Compiling Cookbooks...
    Converging 1 resources
    Recipe: git::package
      * git_client[default] action install
        * apt_package[default :create git] action install (up to date)
         (up to date)

    Running handlers:
    Running handlers complete
    Chef Infra Client finished, 0/2 resources updated in 10 seconds



>knife job status
    command:     chef-client -r recipe[git]
    created_at:  Thu, 21 May 2020 13:14:32 GMT
    env:
    id:          a2b87f87052d213c0703eadb21bdf20e
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Thu, 21 May 2020 13:14:32 GMT

    command:     my_script.sh
    created_at:  Thu, 21 May 2020 13:21:48 GMT
    env:
    id:          a2b87f87052d40e1ca44e6f89a9c97df
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Thu, 21 May 2020 13:21:48 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:29:02 GMT
    env:
    id:          a2b87f87052d8d0b2244b0302a8484e6
    run_timeout: 10
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:29:03 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:30:55 GMT
    env:
    id:          a2b87f87052df522c3901a799290dfed
    run_timeout: 10
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:30:55 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:32:01 GMT
    env:
    id:          a2b87f87052db31d7824a30f11505c55
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:32:01 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:34:04 GMT
    env:
    id:          a2b87f87052d522ad93f478035bee041
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:34:04 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:35:32 GMT
    env:
    id:          a2b87f87052d42f71fd13b8032a7b054
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:35:33 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:38:51 GMT
    dir:         /home
    env:
    id:          a2b87f87052de6f5441df55e3d618abf
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:38:52 GMT

    command:        list_files_script.sh
    created_at:     Fri, 22 May 2020 03:40:34 GMT
    env:
    file_specified: true
    id:             a2b87f87052d2bf179809add21efac1d
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 03:40:34 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:43:13 GMT
    env:
      test: foo
    id:          a2b87f87052d425d844807b50771d734
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:43:13 GMT

    capture_output: true
    command:        stdout
    created_at:     Fri, 22 May 2020 03:45:24 GMT
    env:
    id:             a2b87f87052db06ed3d70d89b3d1fd5a
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 03:45:24 GMT

    capture_output: true
    command:        stdout
    created_at:     Fri, 22 May 2020 03:47:25 GMT
    env:
    id:             a2b87f87052d88eb354cb36cabce85c0
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 03:47:26 GMT

    capture_output: true
    command:        list_files_script.sh
    created_at:     Fri, 22 May 2020 03:49:50 GMT
    env:
    id:             a2b87f87052df864f5064ff041b38308
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 03:49:51 GMT

    capture_output: true
    command:        ls
    created_at:     Fri, 22 May 2020 03:51:06 GMT
    env:
    id:             a2b87f87052d9979c2077b2f4fef7576
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 03:51:06 GMT

    command:     chef-client
    created_at:  Fri, 22 May 2020 05:38:56 GMT
    env:
    id:          a2b87f87052d85fdc332936e82b794e3
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 05:38:56 GMT

    command:     chef-client
    created_at:  Fri, 22 May 2020 06:03:09 GMT
    env:
    id:          a2b87f87052db9a3c5b4a2b4bb79e03a
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 06:03:09 GMT

    command:     add-glasses
    created_at:  Fri, 22 May 2020 06:07:05 GMT
    env:
    id:          a2b87f87052d75bf913276985aefe65f
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 06:07:05 GMT

    capture_output: true
    command:        ls
    created_at:     Fri, 22 May 2020 06:27:19 GMT
    env:
    id:             a2b87f87052db42c167a05b4df53c486
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 06:27:20 GMT

    capture_output: true
    command:        my_script.sh
    created_at:     Fri, 22 May 2020 06:36:20 GMT
    env:
    id:             a2b87f87052dcdb2edec27cffe229bcb
    run_timeout:    3600
    status:         quorum_failed
    updated_at:     Fri, 22 May 2020 06:36:20 GMT

    command:     chef-client
    created_at:  Fri, 22 May 2020 06:42:42 GMT
    env:
    id:          a2b87f87052d042dbd3b90f23b02e832
    run_timeout: 3600
    status:      complete
    updated_at:  Fri, 22 May 2020 06:43:15 GMT

    capture_output: true
    command:        chef-client
    created_at:     Fri, 22 May 2020 06:48:28 GMT
    env:
    id:             a2b87f87052d3ad55eff906e1c0225de
    run_timeout:    3600
    status:         complete
    updated_at:     Fri, 22 May 2020 06:48:46 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:41:52 GMT
    id:          a2b87f87052d194cedae3700b8115bc7
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:41:52 GMT

    command:     list_files_script.sh
    created_at:  Fri, 22 May 2020 03:37:04 GMT
    id:          a2b87f87052d7d6735163272c1d39915
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 03:37:05 GMT



>knife job status a2b87f87052d3ad55eff906e1c0225de
    capture_output: true
    command:        chef-client
    created_at:     Fri, 22 May 2020 06:48:28 GMT
    env:
    id:             a2b87f87052d3ad55eff906e1c0225de
    nodes:
      succeeded: node-push-job
    run_timeout:    3600
    status:         complete
    updated_at:     Fri, 22 May 2020 06:48:46 GMT

>knife job status a2b87f87052d3ad55eff906e1c0225de node-push-job
    capture_output: true
    command:        chef-client
    created_at:     Fri, 22 May 2020 06:48:28 GMT
    env:
    id:             a2b87f87052d3ad55eff906e1c0225de
    nodes:
      succeeded: node-push-job
    run_timeout:    3600
    status:         complete
    updated_at:     Fri, 22 May 2020 06:48:46 GMT



>knife job start --quorum 80% 'chef-client' -s 'name:node-git'
    /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-push-1.1.5/lib/chef/knife/job_helpers.rb:25: warning: URI.escape is obsolete
    Started.  Job ID: a2b87f87052d47a145a45081a22b2127
    .Quorum_failed.
    command:     chef-client
    created_at:  Fri, 22 May 2020 10:38:45 GMT
    env:
    id:          a2b87f87052d47a145a45081a22b2127
    nodes:
      unavailable: node-git
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 10:38:45 GMT


>knife job start --quorum 80% 'chef-client' --search 'name:node-git'
    /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-push-1.1.5/lib/chef/knife/job_helpers.rb:25: warning: URI.escape is obsolete
    Started.  Job ID: a2b87f87052d071b3f3b87d210ca2470
    .Quorum_failed.
    command:     chef-client
    created_at:  Fri, 22 May 2020 10:40:44 GMT
    env:
    id:          a2b87f87052d071b3f3b87d210ca2470
    nodes:
      unavailable: node-git
    run_timeout: 3600
    status:      quorum_failed
    updated_at:  Fri, 22 May 2020 10:40:44 GMT

**Comment by vsingh-msys** [comment]
Looks good to me. Closing for now

**Comment by btm** [comment]
> /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-push-1.1.5/lib/chef/knife/job_start.rb:116: warning: constant Net::HTTPServerException is deprecated

@vsingh-msys we should fix that.

**Comment by vsingh-msys** [comment]
Yes, I was under impression that we are only focused on ruby 2.7 related issues & warning. thanks for pointing it out. 

Created PR https://github.com/chef/knife-push/pull/74 to fix.
