### ISSUE TITLE
config.rb or config.toml?

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-workstation#1217]
## Description

Docs issue reported in Success Slack conversation
The web docs saying the config is in config.rb, when the app itself tells you the config is config.toml.

```
# chef-run
Creating config file in /root/.chef-workstation/config.toml.
chef-run reads your local ~/.chef/config.rb and looks for cookbooks in the paths specified as cookbook_path. That configuration value is an array and looks something like this:
```
https://www.chef.sh/docs/chef-workstation/chef-run-users-guide/#running-a-recipe

in the toml it is cookbook_repo_paths
so which one is it ? config,rb, config.toml ? both ?  which order ? (edited)

**Comment by mudash** [comment]
In short, `chef-run` looks in both `config.toml` and `config.rb` files. Preference is given to `config.toml` file. If a recipe is not found there then path from `config.rb ` is used.

**Details and Example:**

There is a recipe called `filer` under the cookbook `tcb`. It exists at two location: `~/learn-chef-rally/cookbooks` and `/tmp/cookbooks`

Following path is available in `~/.chef/config.rb`

`cookbook_path            ["#{current_dir}/../cookbooks", "~/learn-chef-rally/cookbooks"]`

`~/.chef-workstation/config.toml` contains the following configuration
```
[chef]
cookbook_repo_paths="/tmp/cookbooks"
```
Upon running the `chef-run` the path from config.toml is given precedence:

`bundle exec bin/chef-run ubuntu1 tcb::filer
[✔] Packaging cookbook... done!
[✔] Generating local policyfile... exporting... done!
[✔] Applying tcb::filer from /tmp/cookbooks/tcb to target.
└── [✔] [ubuntu1] Successfully converged tcb::filer.`

**Comment by tyler-ball** [comment]
Thanks Mudassar - we'll get https://docs.chef.io/workstation/chef_run/ updated (the non-microsite version) to reflect the precedence order.
