### ISSUE TITLE
Throwing warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by MrCyrus** [chef/chef-workstation#1282]
## Description

Running 'kitchen test' from chef-workstation 20.6.62 is throwing multiple warnings of:
/var/lib/jenkins/.chefdk/gem/ruby/2.7.0/gems/vsphere-automation-runtime-0.4.6/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete

I see 1 warning before the VM create
I see 8 warnings during the VM create
I see 5 warnings during the VM destroy

## Chef Workstation Version

20.6.62

## Platform Version

RedHat 6, Ubuntu 18.04, Amazon Linux 2 AMI

**Comment by clintoncwolfe** [comment]
Could you post an anonymized version of your kitchen.yml, and your Gemfile, if any? I'm not clear on what driver you're using.

**Comment by MrCyrus** [comment]
The cookbook with the issues has no Gemfile.
The .kitchen.yml file is:
---
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USERNAME'] %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] %>
  vcenter_host: <%= ENV['VCENTER_HOST'] %>
  vcenter_disable_ssl_verify: true
  folder: <%= ENV['FOLDER'] %>
  datacenter: <%= ENV['DATACENTER'] %>
  network_name: <%= ENV['NETWORK_NAME'] %>
  targethost: <%= ENV['TARGETHOST'] %>
  resource_pool: <%= ENV['RESOURCE_POOL'] %>
  customize:
    annotation: "Kitchen VM by <%= ENV['USER'] %> on <%= Time.now.to_s %>"

transport:
  username: vagrant
  password: vagrant
  connection_timeout: 90

provisioner:
  name: chef_zero

verifier:
  name: inspec
platforms:
  - name: rhel-6
    driver:
      template: Templates/ltcosapkitrh6.is.agilent.net
      clone_type: linked

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    run_list:
      - recipe[jenkins_testing::default]

Tait Cyrus | Automation Specialist | Tata Consultancy Services
Work: +1 719-531-4560 | Webex: https://agilent.webex.com/join/tait.cyrus

**Comment by collinmcneese** [comment]
I created a PR to update this for the VMWare gem `vsphere-automation-sdk-ruby` which is what is using this deprecated method:
https://github.com/vmware/vsphere-automation-sdk-ruby/pull/73

**Comment by collinmcneese** [comment]
VMWare merged changes in and release `vsphere-automation-sdk-ruby` version `0.4.7` which corrects this error.  This will be included in the next release of Chef Workstation which will clear up the warning output.

```
# Using 'current' release build (not yet stable)
vagrant@default-ubuntu-2004:~$ chef gem list | grep vsphere-automation-runtime
vsphere-automation-runtime (0.4.7)
vagrant@default-ubuntu-2004:~$ chef --version
Chef Workstation version: 20.7.96
Chef Infra Client version: 16.2.73
Chef InSpec version: 4.21.3
Chef CLI version: 3.0.11
Test Kitchen version: 2.5.3
Cookstyle version: 6.12.6

```

**Comment by tyler-ball** [comment]
Closing this out because the latest release of Chef Workstation (`20.7.96`) includes the version of `vsphere-automation-sdk` that Collin linked. Thanks for getting that issue fixed on their side!
