### ISSUE TITLE
"Getting Started" page isn't for Workstation 

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation#1293]
See: https://docs.chef.io/workstation/getting_started/

This looks like it got pulled in at some point from very old  chef  docs. Maybe we could consider removing it, or replacing the content with the 'getting started' section of 'about chef workstation'?

Aha! Link: https://chef.aha.io/features/SH-2418

**Comment by tyler-ball** [comment]
It looks like there is some valuable information in that page, along with some copy-pasta errors. I propose we do a cleanup pass and decide what we want to keep/merge with the 'about chef workstation' page.

**Comment by tas50** [comment]
We did a basic cleanup of this page so that it doesn't recommend anything totally wrong
