### ISSUE TITLE
Assess Impact on WS for macOS 11 and Apple Silicon

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1300]
#### Note: GitHub integration record type. Please leave out any sensitive information.  
  
  
Job to be Done:

As a Chef operator,
I want to manage my Chef infrastructure from my new Big Sur laptop,
So that I can continue supporting my companies IP using the latest workstations available.

#### Description:

MacOS 11 (Big Sur) is releasing in September or October 2020. As with previous MacOS upgrades we need to test out this operating system with Chef Workstation and ensure it still has 100% functionality.

Apple is also releasing their new ARM chips and we want to ensure Chef Workstation is functional and equivalently fast on this new architecture.

#### Acceptance Criteria:

1. Pipeline updated with Big Sur testers so we can automatically test builds
2. Big Sur test box to install Chef Workstation packages on
3. Test for known existing breakages
    1. Permission changes - previous MacOS updates have changed what folders we can/cannot write to (/opt, /tmp, etc.)
    1. Entitlement changes - do we need new entitlements for our software to have full functionality?
    1. Software compilation - need to ensure Ruby, GoLang, and Electron apps can build and execute successfully
1. General use testing. We need to setup Big Sur as a daily driver and ensure general workstation usage does not uncover any issues.
1. Apple Silicon general use testing. Ensure our x86_64 package works using the translation layer.
1. Test native Apple Silicon builds and compare their speed to the translated packages.
1. Test a universal binary (both x86_64 and arm64 executables) and see how large it is.
1. Decide whether to create a Apple Silicon, a universal package, or recommend customers install the x86_64 version.
1. Ensure existing download tools (downloads.chef.io, omnitruck, etc.) interpret the new Apple Silicon architecture and serve the appropriate package

## Resources

https://developer.apple.com/documentation/xcode/porting_your_macos_apps_to_apple_silicon
https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

Aha! Link: https://chef.aha.io/features/SH-143

**Comment by tas50** [comment]
We are building for big sur currently and tracking an M1 upgrade
