### ISSUE TITLE
Investigate Big Sur pipeline testing capabilities

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1305]
## Description

Our current model for building packages only builds on 1 version of an operating system (EG, MacOS 10.12) but tests on every version of that operating system we release a package for. But Big Sur is a major version bump so we want to ensure we set aside time to guarantee our pipeline can support this and successfully generate packages.

## Acceptance Criteria

1. Sync with RelEng on timeline for adding Big Sur testers to pipeline. Do we need to do anything to support that?
1. Ensure pipeline can successfully test packages on Big Sur (IE, pipeline is green).

## Notes

The complexity and unknown/risk in this card all comes down to whether we have any issues building on Big Sur, and what those issues are.

Aha! Link: https://chef.aha.io/features/SH-2458

**Comment by tas50** [comment]
We're producing big sur packages now
