### ISSUE TITLE
Manual validation for Big Sur packages

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1306]
## Description

Automated testing will not cover all use cases, so we want to perform manual validation of the Chef Workstation Big Sur packages.

## Acceptance Criteria

1. Test for known existing breakages
    1. Permission changes - previous MacOS updates have changed what folders we can/cannot write to (/opt, /tmp, etc.)
    1. Entitlement changes - do we need new entitlements for our software to have full functionality?
    1. Software compilation - need to ensure Ruby, GoLang, and Electron apps can build and execute successfully
1. General use testing. We need to setup Big Sur as a daily driver and ensure general workstation usage does not uncover any issues.

Aha! Link: https://chef.aha.io/features/SH-2459

**Comment by tas50** [comment]
Big sur has been tested as working
