### ISSUE TITLE
[Test Kitchen] Users can specify the directory where chef-installer.sh is executed from

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1319]
## Description
Implementation card for results from spike https://github.com/test-kitchen/test-kitchen/issues/1661

## Acceptance Criteria

1. When users specify `root_path` then the chef installer script will be written to and executed from that folder
1. This work for installing chef using the `product_name` (mixlib-install based) install method
1. Verify this fix works with kitchen-vagrant, kitchen-ec2, and kitchen-dokken
1. Execute the `chef-installer.sh` using sudo, instead of adding a sudo command to every line in that file
    1. If the `root_path` is not writable by the configured transport user, raise a good error telling them to either change their `root_path` or change their transport user to one who can write to that path

Closes customer-bugs 4

## Notes

We specifically want to test this fix for kitchen-ec2 because a previous fix was [reverted](https://github.com/test-kitchen/test-kitchen/pull/1403) because the tests use kitchen-dokken which bypass this code path. We also validated that the issue is present in kitchen-vagrant.

One of the potential fixes that we don't like adds a `sudo` command to every line in the installer file. This seems unnecessary and cumbersome, so we want to revert that.

**Comment by clintoncwolfe** [comment]
Here's the error raised when the path is not creatable:
```
mkdir: cannot create directory ‘/home/nosuchluck’: Permission denied
Kitchen config setting root_path: /home/nosuchluck/kitchen not creatable by regular user
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-2004>.  Please see .kitchen/logs/default-ubuntu-2004.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
The script then exits immediately, and kitchen goes into error recovery.
