### ISSUE TITLE
Improvements to Chef Analyze code base

### ISSUE THREAD

**Issue by mudash** [chef/chef-workstation#1322]
Suggested improvements:

- Refactor this function for cookbooks report 
```
func NewCookbooksReport(
	cbi CookbookInterface, cbai CBAInterface, pgi PolicyGroupInterface, poi PolicyInterface, searcher SearchInterface,
	runCookstyle bool, onlyUnused bool, workers int,
	nodeFilter string, anonymize bool,
```
- Revisit and rename `NewDefault()` function whose main task is to read the configuration file and override any defaults

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-analyze/pull/322
