### ISSUE TITLE
Document MSI installer flags

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1357]
## Description

Windows users who want to do an unattended install can pass command line flags when installing Chef Workstation. These flags can toggle all the settings that can be toggled via the wizard-based-installer.

But we do not document anywhere what these flags are and what they do.

## Acceptance Criteria

1. Document Windows installer flags on docs.chef.io
1. All flags should have a description, what values can be passed, and what each flag does.
1. Test these flags to ensure each one works.
1. Timebox this to 2 points.

**Comment by tyler-ball** [comment]
Lets timebox this since the customer figured out the flag they need to specify. If those flags are exposed, can we just add a section to the documentation titled `How to do an unattended install on Windows`?

**Comment by marcparadise** [comment]
I agree; the available flags are  covered in MSI installer docs already, and most of them would only serve to break the install in various ways.   

Unattended and headless installs are a supported method of installation, though, and we should provide info on how to do that.

**Comment by marcparadise** [comment]
https://github.com/chef/chef-workstation/pull/1418
