### ISSUE TITLE
Assess impact to Chef kit and patterns in support of Apple's transition to ARM 

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1364]
#### Note: GitHub integration record type. Please leave out any sensitive information.  
  
  
Job to be Done:

As an <persona>,

I want to <job to be done>

So that <reason for needing job/benefit>

#### Description:

<additional details>

#### Acceptance Criteria:

1.

2.

3.

Aha! Link: https://chef.aha.io/features/SH-138

**Comment by tas50** [comment]
Closing this out as we're handling this infra wide now
