### ISSUE TITLE
[SPIKE] Remove Administrator requirements from Chef Powershell shortcut

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1365]
## Description

Some Windows Chef Workstation customers run in a non-administrator environment. Trying to execute the Chef Workstation shortcut we add to their desktop on installation causes two errors:

1. The '-verb runas' in the shortcut requires the user to have Administrator privilege. Is this even necessary to run most of the tools in Chef Workstation? Chef Infra Client requires administrator privileges to manage a system, but if a user is only writing cookbooks and testing them with Test Kitchen I do not think they need Administrator privileges.
1. When users previously had local admin rights but simply lift-clicked on the Desktop shortcut they would get an error about "running scripts is disabled on this system, see about_Execution_Policies" (see attached screenshot) Right-clicking + run as admin would not give that same script error for some users.

## Acceptance Criteria

* Determine how much % of the Chef Workstation kit requires users to have Administrator privilege to access
    * If this is low, file a card to remove the Administrator requirement from our shortcut
    * If this is high, add documentation in the code of the shortcut as to why we ask for Administrator privilege
* Is there some way we could inline the script so we don't need the separate script and the execution policy?
    * If not, could we give them a better warning/error about what setting they need and how to apply it? `Try setting the execution policy by running....`

**Comment by marcparadise** [comment]
I may be missing something here, but it looks like if you're not running chef-client to converge your local machine, you shouldn't ever _need_ admin to use Workstation tools.

**Comment by tyler-ball** [comment]
Does `hab` require Administrator privileges? It installs packages into a hab owned folder, but does it need Admin privileges to create that folder?

**Comment by marcparadise** [comment]
I have verified that habitat is mostly OK without admin. Some operations (starting a supervisor) may prompt for admin rights and will fail without, but basic operations (installs and updates) worked without admin. 

Given that Windows UAC will prompt when the hab executable needs escalated privileges, I don't think this will block moving forward with removing the admin requirement.

**Comment by marcparadise** [comment]
Opened https://github.com/chef/chef-workstation/issues/1449 for track next steps.
