### ISSUE TITLE
[Test Kitchen] Retry fixing root_path

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1377]
## Description

* Original issue - https://github.com/chef/chef-workstation/issues/1319
* Original PR to fix it - https://github.com/test-kitchen/test-kitchen/pull/1662
* TK issue showing repro steps for Windows - https://github.com/test-kitchen/test-kitchen/issues/1665

Looks like the fix worked for non-Windows... hosts? Targets? I'm not sure, we need to figure that out

## Acceptance Criteria

1. Fix the original issue of `root_path` not being respected, and ensure it works for a full *nix/Windows matrix
1. Add CI testing to catch this issue in the future. Test the full chef-client install on Windows, *nix (we currently only test a chef-zero install in CI).

## Related issues

* Closes customer-bugs 4

**Comment by clintoncwolfe** [comment]
CI improvements are on test-kitchen/test-kitchen#1668

Fix for regression is on test-kitchen/test-kitchen#1669
