### ISSUE TITLE
Kitchen test not honoring product_version when download_url is specified

### ISSUE THREAD

**Issue by lukeseawalker** [chef/chef-workstation#1390]
## Description
Hi,
I'm trying to specify a Chef client version in the Kitchen test provisioner, together with a `download_url` (in the following example I'm just using the default `download_url` to show that it's not a problem with my custom download URL).
Despite the `product_version` set to 15.11.8, the downloaded version is the latest.

I'm using chef-workstation `20.7.96`.

```
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 15.11.8
  download_url: https://omnitruck.chef.io/install.sh
```

snippet of the log

```
       Download URL override specified
       /tmp/kitchen/install.sh not found
       downloading https://omnitruck.chef.io/install.sh
         to file /tmp/kitchen/install.sh
       trying wget...
       Installing chef 15.11.8
       installing with sh...
       el 6 x86_64
       Getting information for chef stable  for el...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=6&m=x86_64
         to file /tmp/install.sh.3579/metadata.txt
       trying wget...
       sha1	ddf703b0965a6e4ff6801a83db850bd7d8b7ade9
       sha256	6ac3f32541ecd869dd7ba25b98399de8df5c9ecf54038eddae4f209b2f57a007
       url	https://packages.chef.io/files/stable/chef/16.3.45/el/6/chef-16.3.45-1.el6.x86_64.rpm
       version	16.3.45
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/files/stable/chef/16.3.45/el/6/chef-16.3.45-1.el6.x86_64.rpm
         to file /tmp/install.sh.3579/chef-16.3.45-1.el6.x86_64.rpm
       trying wget...
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing a package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
```

When removing the `download_url` parameter the version is honored.
```
       Getting information for chef stable 15.11.8 for el...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=15.11.8&p=el&pv=6&m=x86_64
         to file /tmp/kitchen/metadata.txt
       trying wget...
       sha1	ad96b3e3938fbc3a997aad8d633ce7bc66633296
       sha256	8bddb59f6d1f630c5a4864f430f0cbde4a92fee383c5bc63afb9f87214af71d5
       url	https://packages.chef.io/files/stable/chef/15.11.8/el/6/chef-15.11.8-1.el6.x86_64.rpm
       version	15.11.8
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/files/stable/chef/15.11.8/el/6/chef-15.11.8-1.el6.x86_64.rpm
         to file /tmp/kitchen/chef-15.11.8-1.el6.x86_64.rpm
       trying wget...
       Comparing checksum with sha256sum...
       Installing chef 15.11.8
       installing with rpm...
       warning: /tmp/kitchen/chef-15.11.8-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
       Preparing...                          ################################# [100%]
       Updating / installing...
          1:chef-15.11.8-1.el6               ################################# [100%]
       Thank you for installing Chef Infra Client! For help getting started visit https://learn.chef.io
```

## Chef Workstation Version
chef-workstation 20.7.96-1

## Platform Version
MacOS

**Comment by tyler-ball** [comment]
Hey @lukeseawalker, thanks for filing an issue. If you provide `download_url` it expects the full path a downloadable executable. You can also provide `checksum` to validate the file contents. Can you try that usage and see if it fixes your issue?

The side effect of this is that you cannot provide a custom link for an `installer.sh` type script.

**Comment by lukeseawalker** [comment]
Thank you for answering @tyler-ball.
Ok I got it, I was misinterpreting that `download_url` had replaced `chef_omnibus_url`.
Is there a way to parameterize `download_url` in order to download the right package? We do have multiple platform to test and so the executable must be different depending on the platform family.

For now I think I'll go back in using the deprecated `require_chef_omnibus` and `chef_omnibus_url`. Do you know up to which version they will be still usable? Is there any plan to restore a parameter to specify a custom omnibus installation script?

Thanks,
L

**Comment by tyler-ball** [comment]
We don't have any current plans to remove `require_chef_omnibus` and it will probably be supported for the foreseeable future. 

Pinging @clintoncwolfe to get his opinion on using `product_name`/`product_version` with a custom `install.sh` script. Is there some reason those options do not work for you? Can you speak more about your use case and what is missing in the current configuration options?

**Comment by lukeseawalker** [comment]
Use cases are different, for example:
* we are adding some custom logic before the package installation, e.g. for Ubuntu we are checking that the automatic update are ended before installing the client, otherwise we get a dpkg lock issue
* we want to host the package on different endpoint for the case with no Internet access

**Comment by tyler-ball** [comment]
I'm glad you were able to get the configuration working for your use case!
