### ISSUE TITLE
[test-kitchen] Toggle concurrency per-plugin

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/chef-workstation#1442]
### Describe the Enhancement:

When using the `-c-` concurrency feature, some Kitchen plugins appear to be thread-unsafe, but TK assumes all are thread-safe. This results in unreliability.

### Describe the Need:

As a chef infra operator 
I want to test a cookbook in parallel on multiple platforms
In a way that is as fast and stable as possible
So that I save time and have reliable results

### Current Alternative

Run Test kitchen using external parallelization

### Acceptance Criteria
 1. TK core has been modified to detect when a requested action is not thread-safe and will run that action serially (tracks test-kitchen/test-kitchen#1677)
 2. Audit the following plugins and determine if they exhibit non-thread-safe behavior. If they do, mark them as 'serial'
    * `kitchen-vcenter` (appears fine)
    * `kitchen-inspec` ([existing issue](https://github.com/inspec/kitchen-inspec/issues/167))
    * `chef-solo` provisioner [issue](https://github.com/test-kitchen/test-kitchen/issues/1680)
3. Ensure that `kitchen-dokken` and `kitchen-vagrant` exhibit stability when ran together with changes made to the previously listed plugins. IE, the combination of `kitchen-vagrant` and `kitchen-inspec` may run slower (because InSpec will run serially) but it should execute with `-c` correctly now.

### Related Issues

#1404

**Comment by clintoncwolfe** [comment]
It appears kitchen-dokken's provisioner is non-thread-safe, or else chef-zero is, see https://github.com/test-kitchen/kitchen-dokken/issues/203

**Comment by tyler-ball** [comment]
Ready for review - test-kitchen/test-kitchen#1678
