### ISSUE TITLE
Universal binary build of zlib

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1453]
## Description

As part of #1451 we need to build universal binaries of all the executables and libraries embedded inside Chef Workstation. To give us some idea of how to do that, we looked at the serialized list of components in Chef Workstation and picked the first one to use as a testbed.

## Acceptance Criteria

1. Explore and communicate to the team how to manually generate an `arm64` version of the `zlib` libraries. Ensure we understand the build time requirements to do this.
    1. Ensure our builders contain the necessary tools to generate a universal binary. If they do not, file a new card to work with RelEng and ensure we get those tools installed.
1. Prototype a pattern we could apply to the `omnibus` and `omnibus-software` libraries to build two executables (`amd64` and `arm64`) and link them into a universal executable using the `lipo` tool.
    1. This pattern should require minimal change to the omnibus software definitions to support universal binaries. Perhaps there is just an `omnibus.rb` flag users need to set in order to start generating universal binaries?

## Notes

We guess that a big part of converting all our required omnibus software definitions is going to depend on how the underlying project setup its `Makefile`. We want to start getting an idea of what we would need to do to support `arm64` builds but this card should not be an exhaustive audit of all existing software definitions.

**Comment by tas50** [comment]
Closing this as we're handling this all on the infra side
