### ISSUE TITLE
[SPIKE] How are the existing Automate dev/acceptance environments managed?

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1458]
## Acceptance Criteria

Answer the following questions:

1. How are the Automate and Chef Server dev/acceptance environments managed? We need to understand that to understand how much new work there is to manually test #1394
    1. If the answer is 'no', brainstorm and decide how/where to create Chef Server and Automate for #1394
1. Do those existing environments have any nodes setup to run chef-client? Are they setup with Policyfiles? We also need to understand what new work there is to setup nodes for consuming Policyfile updates.

**Comment by tyler-ball** [comment]
Can we introduce a new tile into the dev/acceptance environment listings so we have a dedicated place for automated testing in the future?

**Comment by tas50** [comment]
Closing this out since we won't be working on it now
