### ISSUE TITLE
Running knife command from workstation fails

### ISSUE THREAD

**Issue by zr2d2** [chef/chef-workstation#1531]
## Description
When I try to run a `knife` command in a CW PowerShell window I get an error

## Chef Workstation Version
20.10.169

## Platform Version
Windows 10.0.18363

running a knife command in a workstation window gives me an SystemAccessViolation error
![chef-error](https://user-images.githubusercontent.com/189034/98385737-52c95a00-201d-11eb-9830-47fad392b83d.png)

**Comment by marcparadise** [comment]
Thanks for reporting this @zr2d2, can you confirm that it's still occurring for you on the latest versions of Workstation? We have not been able to reproduce this locally.

**Comment by zr2d2** [comment]
It is not still happening, I think the corporate endpoint protection was killing the knife process, iirc.
