### ISSUE TITLE
kitchen VRO not working after upgrading to chefdk-4.12.0-1

### ISSUE THREAD

**Issue by vineethp088** [chef/chef-workstation#1553]
kitchen vro not working after upgrading to chefdk-4.12

Upgraded from chefdk-2.4 to chefdk-4.12

We are using the VRO driver

E, [2020-11-02T11:59:46.474894 #2519] ERROR -- Kitchen: ------Exception-------
E, [2020-11-02T11:59:46.475032 #2519] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2020-11-02T11:59:46.475058 #2519] ERROR -- Kitchen: Message: Could not load the 'vro' driver from the load path. Did you mean: azur
erm, digitalocean, dokken, dummy, ec2, exec, gce, hyperv, proxy, ssh_base, vagrant ? Please ensure that your driver is installed as a g
em or included in your Gemfile if using Bundler.

E, [2020-11-02T11:59:46.475542 #2519] ERROR -- Kitchen: Class: Gem::ConflictError
E, [2020-11-02T11:59:46.475566 #2519] ERROR -- Kitchen: Message: Unable to activate kitchen-vro-1.0.0, because test-kitchen-2.7.2 conflicts with test-kitchen (~> 1.4, >= 1.4.1)
E, [2020-11-02T11:59:46.475590 #2519] ERROR -- Kitchen: ----------------------

Looks some dependency here ? https://github.com/chef-partners/kitchen-vro/blob/master/kitchen-vro.gemspec#L22 as the error message says "Unable to activate kitchen-vro-1.0.0, because test-kitchen-2.7.2 conflicts with test-kitchen (~> 1.4, >= 1.4.1)"

**Comment by clintoncwolfe** [comment]
Hi, I apologize that you are experiencing difficulty. However, my understanding is that kitchen-vro is not currently maintained. vmware users are encouraged to explore [kitchen-vcenter](https://github.com/chef/kitchen-vcenter) as the supported future path.  

Likewise, chef-dk is now deprecated, and has been replaced by Chef Workstation. Chef Workstation includes several maintained drivers for test kitchen, including kitchen-vcenter, the vmware driver.

I'm sorry that change will be needed, and that you will see less automation from kitchen-vcenter than kitchen-vro. One more automated option might also be kitchen-terraform with some sort of vmware provider, but I am only speculating.

**Comment by marcparadise** [comment]
This will not be addressed, as kitchen-vcenter replaces kitchen-vro.
