### ISSUE TITLE
kitchen-dokken is broken

### ISSUE THREAD

**Issue by docwhat** [chef/chef-workstation#1570]
## Description

`kitchen-dokken` 2.11.1 does not work.  See test-kitchen/kitchen-dokken#208 for more information.

## Chef Workstation Version

```sh
❯ chef --version
Chef Workstation version: 20.11.180
Chef Infra Client version: 16.6.14
Chef InSpec version: 4.23.15
Chef CLI version: 3.0.33
Chef Habitat version: 1.6.56
Test Kitchen version: 2.7.2
Cookstyle version: 7.2.1
```

## Platform Version

macOS 10.15.7 (Catalina)

**Comment by tas50** [comment]
This was fixed in the latest release of workstation by working around the changes that happened in the docker api
