### ISSUE TITLE
Tracking: identify arm64-incompatible components via omnibus build of Workstation on DTK node

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation#1573]
In order to provide a native build for Apple's M1 chip, all of the components that are included in a Workstation build must have builds that are compatible with ARM64.   Because we don't own most of the components we include (they are third party open source projects), we don't have direct control over this.  

However, we do need to identify which components are able to build, and which of those have dependencies upstream. 

Once we make this determination, we can start tracking those projects, and potentially submit upstream patches. 

To determine which components can build, we will need to uset he DTK node we have available and start working through the process of running an omnibus build. As components fail, we can track them in this card. 

Because there is a long chain of build dependencies, a failed component can prevent subsequent components from building.  When this happens, it may be necessary to patch the failed component (if reasonably possible) to continue; or otherwise attempt to build subsequent components directly without using the omnibus build. 

This will be an iterative card that will probably span more than one sprint.

**Comment by tas50** [comment]
Closing this out so we can track the work in the chef/chef repo instead
