### ISSUE TITLE
CLI help text for <RECIPE> name is missing an expected format 

### ISSUE THREAD

**Issue by stuartpreston** [chef/chef-workstation#168]
# Version
0.1.120

# Description 
The 3rd variant of `<RECIPE>` in the help text does not provide the required format in the text.

```
  <RECIPE>          The recipe to converge. This can be provided as one of:
                    1. Full path to a recipe file
                    2. Cookbook name. First we check the working directory for this
                       cookbook, then we check in the chef repository path. If a
                       cookbook is found we run the default recipe.
                    3. This behaves similarly to 'cookbook name' above, but it also allows
                       you to specify which recipe to use from the cookbook.
```
# Expected

Variant 3 should provide an explanation that the required format is `cookbook name::recipename`

**Comment by tyler-ball** [comment]
Thanks @stuartpreston - this is still an issue in the latest version. The examples shown above this block show `chef-run web01 cookbook_name::recipe_name` but this help text definitely needs some cleanup. Triaging so we can get it fixed!

**Comment by tyler-ball** [comment]
The fix will need to occur in https://github.com/chef/chef-apply but we'll link a PR back to here when we fix it.

**Comment by nikhil2611** [comment]
Fixed: [https://github.com/chef/chef-apply/pull/153](url)
