### ISSUE TITLE
Feature Request: chef-run target a hostname in my ssh config

### ISSUE THREAD

**Issue by kmf** [chef/chef-workstation#172]
When I target host that's specified in my ssh config I get a timeout?
Can this be a feature request?

```
[✖] [magic-name-sshconfig] SSH session could not be established

CHEFINT001

An remote error has occurred:

  SSH session could not be established.

If you are not able to resolve this issue, please contact Chef support
at beta@chef.io and include the log file and stack trace from the
locations below:

  /home/kmf/.chef-workstation/logs/default.log
  /home/kmf/.chef-workstation/logs/stack-trace.log
```

**Comment by cheeseplus** [comment]
What does the ssh/config file look like? I used ssh config for the hostnames during the demo so we're fairy confident that this works for at least that - picking up keys and usernames automatically may not work at this time.

**Comment by kmf** [comment]
Host OS: ```Ubuntu 18.04```
Target OS: ```Ubuntu 16.04.3```
chef-run --version: ```chef-run: 0.1.120```

value in ```.ssh/config```
```
Host magic-name-sshconfig
    user someuser
    hostname 46.123.123.123

Host some-other-magic-host
    HostName 10.0.2.21
    User someuser
    ProxyCommand ssh someuser@magic-name-sshconfig nc %h %p
```

**Comment by marcparadise** [comment]
Hey @kmf, sorry it's taken so long to get back to this.  We were in chefconf recovery mode for bit :) Would you be able to attach the default.log and stack-trace.log? That will give us some more details around the failure reason. 

If you don't want to post them publicly you can send them over to us at beta - at - chef.io, or just ping me in the #chef-workstation channel in community slack. (@mparadise)
