### ISSUE TITLE
CONTENT: Do we want to suggest using the embedded Ruby

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1737]
Note: We need to confirm this first with @marcparadise and @lamont-granquist

We need to investigate if in 2021 we want to suggest users run the embedded Ruby installation as their main ruby install. Chef Workstation should work without this and if we can avoid the step we should. It should be an optional step in its own page instead.

**Comment by marcparadise** [comment]
I'd definitely rather we didn't expose Workstation's ruby at all, so I'm +1.  But we do actively encourage it by automatically adding it to the path via `shell-init`.

**Comment by tas50** [comment]
After chatting with lamont as well I think the answer still has to be yes.
