### ISSUE TITLE
CONTENT: Remove mentions of the embedded/bin directories

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1738]
Note: We need to confirm this first with @marcparadise and @lamont-granquist

Our PATH setup instructions currently suggest adding the embedded/bin directory in the Chef Workstation installation to the path. This isn't something we should need to do at this point:

https://docs.chef.io/workstation/getting_started/#add-ruby-to-path

**Comment by marcparadise** [comment]
This seems safe, everything we reference in our tooling is in /bin.  I wonder if this  should also go with a change to `chef-cli shell-init` that no longer adds the embedded/bin dir to the environment path?

**Comment by tas50** [comment]
it sounds like we have a few more things that would need to be moved to bin dir to make it possible to do this. It's a larger thing than just docs.
