### ISSUE TITLE
chef target does not work

### ISSUE THREAD

**Issue by spuder** [chef/chef-workstation#174]
The documentation references a command called `chef target` but that does not work

```
chef target converge <Target host|IP|SSH|WinRM> <Resource> <Resource Name> [properties] [flags]

chef target converge user@hostname user timmy

chef target converge winrm://user@hostname:port user timmy
```

```
chef target converge winrm://foo@example.com
Unknown command `target'.
```

**Comment by marcparadise** [comment]
Thanks for pointing this out, this is the result of the README being out of sync.  We'll get that updated.

**Comment by marcparadise** [comment]
I think the last of these have been evicted, please re-open if you come across any further references to `chef target`.
