### ISSUE TITLE
Feature Request: run against a real chef server

### ISSUE THREAD

**Issue by rj-reilly** [chef/chef-workstation#184]
From the documentation it looks like chef-workstation only runs against local cookbooks:
```
 <RECIPE>          The recipe to converge. This can be provided as one of:
                    1. Full path to a recipe file
                    2. Cookbook name. First we check the working directory for this
                       cookbook, then we check in the chef repository path. If a
                       cookbook is found we run the default recipe.
                    3. This behaves similarly to 'cookbook name' above, but it also allows
                       you to specify which recipe to use from the cookbook.
```
It would be awesome to also be able to use against a chef server, i think it would only work against already bootstrapped nodes, unless workstation is modified to also have the ability to bootstrap. I know there is knife ssh but i think  chef workstation is a better interface and the idea of a inventory file to come is great for orchestration. we currently do this with ansible  as i have found it easier to use than knife ssh for our use case for blue green deployments.

**Comment by cheeseplus** [comment]
As we think about how we re-frame interactions in the context of Workstation we've definitely had the same thought. The challenge here is to align it with or supplant other tooling while still keeping a targeted focus on simplicity, usability, and safety (guiding principles of this initiative). Which is to say this is a good one and we're already thinking about how to do this best.

**Comment by rj-reilly** [comment]
@cheeseplus  i am happy to help with testing when it is ready.

**Comment by robbkidd** [comment]
🤔

@rj-reilly In the meantime, can you share more of your thoughts? In what ways do you find `chef-run` a better interface than `knife ssh` for initiating a chef-client run on multiple hosts already managed with a Chef Server?

**Comment by rj-reilly** [comment]
@robbkidd I guess two things  one is the hostname globbing, second is not having to execute a search when I am trying to put our blue cluster in to production and remove our green, again currently we do this with ansible ( which pains me ) but we have found it to be faster sans the lookup. I am sure there are knife ssh options i may be missing, but i saw the demo at chef conf started playing around with chef-run and liked it.

**Comment by cheeseplus** [comment]
Moved/combined into https://github.com/chef/chef-apply/issues/41
