### ISSUE TITLE
Does not work with ARM chef-client

### ISSUE THREAD

**Issue by rj-reilly** [chef/chef-workstation#185]
When executing against an ARM host that already has chef-client installed chef-run fails with 
```
[✔] [192.168.1.113] Connected.
[✖] [192.168.1.113] Unknown architecture armv7l.
Must be one of: aarch64, i386, powerpc, ppc64, ppc64le, s390x, sparc, x86_64


CHEFINT001

An unexpected error has occurred:

  Unknown architecture armv7l.
Must be one of: aarch64, i386, powerpc, ppc64, ppc64le, s390x, sparc, x86_64
```
Stack trace
```
--------------------------------------------------------------------------------
2018-05-28 21:20:30 -0400: Error encountered while running the following:
  --sudo pi@192.168.1.113 package ntp action=install
Backtrace:
Mixlib::Install::Options::InvalidOptions: Unknown architecture armv7l.
Must be one of: aarch64, i386, powerpc, ppc64, ppc64le, s390x, sparc, x86_64
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/mixlib-install-3.10.0/lib/mixlib/install/options.rb:103:in `validate_options!'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/mixlib-install-3.10.0/lib/mixlib/install/options.rb:92:in `validate!'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/mixlib-install-3.10.0/lib/mixlib/install/options.rb:82:in `initialize'
```

should it work against existing working architectures even if chef-run itself does not execute on ARM ?

**Comment by cheeseplus** [comment]
I think this might only need some casing on our part as it's probably Train vs Ohai platform naming which we've already had to massage prior, just not for architecture.

**Comment by cheeseplus** [comment]
@rj-reilly could you provide some system details from the target system? Ideally run `inspec shell` against the node and that should print platform, arch, and version information.

**Comment by kmf** [comment]
Watching.

**Comment by cheeseplus** [comment]
To be clear, ARM clients aren't really in our priority but the fix itself might be simple as it's got to do with Train vs Mixlib-install naming.

**Comment by rj-reilly** [comment]
@cheeseplus 
`You are currently running on:

    Name:      raspbian
    Families:  debian, linux, unix, os
    Release:   9.4
    Arch:      armv7l
`

**Comment by cheeseplus** [comment]
And which build of chef-client do you normally use @rj-reilly? Link from website or package info would work.

**Comment by rj-reilly** [comment]
I am actually using  ruby 2.5.1 and chef 14.4.56 ( i just reinstalled it ). I have t0 install from gem to build the native extenstions for arm and there is no package for arm. @cheeseplus

**Comment by cheeseplus** [comment]
Ah, then even if we fixed the detection for download this will still fail as we're expecting an omnibus installed chef-client at present.

**Comment by cheeseplus** [comment]
There are actually two pieces here:

1. use `--no-install` to prevent chef-apply from trying to install a chef-client
2. support non-omnibus installs of chef-client, this is tricky because there are lots of ways to install and detection is going to be Fun

Moving the issue over to chef-apply but will link this thread.
