### ISSUE TITLE
gem pristine messages on any command

### ISSUE THREAD

**Issue by eheydrick** [chef/chef-workstation#1854]
## Description
Running any command that comes with chef-workstation results in this message before the output of the command:

```
$ knife node list
Ignoring bcrypt_pbkdf-1.0.1 because its extensions are not built. Try: gem pristine bcrypt_pbkdf --version 1.0.1
Ignoring nokogiri-1.10.9 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.9
```

Same thing for `chef` and `kitchen`. Seems like it started after updating to the previous chef-workstation release.

## Chef Workstation Version

```
$ chef --version
Chef Workstation version: 21.3.346
Chef Infra Client version: 16.11.7
Chef InSpec version: 4.29.3
Chef CLI version: 3.1.3
Chef Habitat version: 1.6.267
Test Kitchen version: 2.11.2
Cookstyle version: 7.10.0
```

## Platform Version

MacOS 10.15.5

**Comment by eheydrick** [comment]
I resolved this by nuking my `~/.chefdk/gem` dir.

**Comment by tas50** [comment]
Closing this out since there was a solution. This is more reason for us to consider nuking the gem dir on reinstall since the libs the gems were compiled against can change and break things.
