### ISSUE TITLE
A2 Self Signed Certificate causes data collector send to fail

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#189]
## Description
When using an A2 server with a self signed certificate the remote `chef-client` run we kick off will hang for an extremely long time, doing nothing. 

## Chef Workstation Version
master

## Platform Version
all

## Replication Case
1. Generate an A2 server using the default setup, so it has a Self Signed certificate
1. Log into the A2 server and generate an API token
1. Paste the token and url into `~/.chef-workstation/config.toml`
```
[data_collector]
url="https://1.1.1.1/data-collector/v0/"
token="****"
```
1. Issue any `chef-run` command against a single node. It will hang trying to perform the Chef run

## Workaround
I got around this issue by applying the following patch locally
```patch
--- a/components/chef-run/lib/chef-run/action/converge_target.rb
+++ b/components/chef-run/lib/chef-run/action/converge_target.rb
@@ -82,6 +82,8 @@ module ChefRun::Action
           data_collector.token "#{dc.token}"
           data_collector.mode :solo
           data_collector.organization "Chef Workstation"
+          verify_api_cert false
+          ssl_verify_mode :verify_none
         EOM
       end
```
All attempts we made to use `knife ssl fetch` on the remote target failed. Maybe the data collector does not use the same trusted certs directory everything else does?

**Comment by tyler-ball** [comment]
Updates: On the target mode we tried `knife ssl fetch` (which put the cert into `~/.chef`) and `sudo knife ssl fetch` (which put the cert into `/root/.chef`). After doing that `knife ssl check` succeeded both with and without sudo, but `chef-client -z` continued to fail. In the `chef-client` output we see:

```
Using policy 'cw_file_policy' at revision '8c36d3da1a051c5488930ff0aeb5fdaa3d6d610a749c01005763bacd4d862069'
[2018-06-19T16:35:55+00:00] ERROR: SSL Validation failure connecting to host: automate - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
resolving cookbooks for run list: ["cw_file::default@0.0.0 (9ca21c3)"]
```

**Comment by jonsmorrow** [comment]
That's how I solved it for demos, but didn't feel we should expose those options to the user? Why let the user shoot themselves.

My thought was when we do the login maybe we can detect the self signed cert and ask the user if they want to trust it. If so we automatically ship it to the target nodes. (but this is longer term)

Short term I wonder if we add a trust_cert config value that can be set and if set set those two values?

Alternatively we can look at the chef-client config and try to debug where it is loading certs from. Maybe our config override is changing that directory.

**Comment by thommay** [comment]
So in traditional bootstrap knife would copy the user's trusted certs from `~/.chef/certs` up to `/etc/chef/certs` which is where it needs to be for chef-client to use it on the target. Maybe if there's an automate url configured it's worth doing the equivalent of `knife ssl check` first on that url and downloading and managing the cert chain?

**Comment by jonsmorrow** [comment]
@thommay Thanks! I think some flavor of that makes sense. I'm a bit nervous about not having the user explicitly agree to trust the self-signed cert, but we can figure that out.

**Comment by thommay** [comment]
yeah you'll certainly need to rub some ux on the whole thing

**Comment by tyler-ball** [comment]
Short term fix in https://github.com/chef/chef-workstation/pull/208

**Comment by tyler-ball** [comment]
Closing this. With latests chef-client and master of chef-apply, this no longer appears to be an issue. This is with trusted certs being forwarded to the target node in a local trusted_certs directory, not putting them in /etc/chef/trusted_certs. Possibly this was fixed by https://github.com/chef/chef-apply/pull/50 ?
