### ISSUE TITLE
Issue with Docker image from 21.4.414+

### ISSUE THREAD

**Issue by bdwyertech** [chef/chef-workstation#1989]
## Description
From container version 4.14.14+, test-kitchen seems to be broken.  When it does a cookbook synchronization to the remote (kitchen-ec2), all files in the cookbooks are empty/blank within the kitchen/cookbooks folder on the remote.  I have done a diff on the two containers and cannot figure it out.  system packages are identical and the diff between workstation 21.4.413 and 414 does not seem to reflect anything which would break this.

Works great on all images up to and including chef/chefworkstation:21.4.413, but its broken on chef/chefworkstation:21.4.414+

```bash
# 21.4.414
[ec2-user@ip-10-1-2-3 ~]$ cat ~/kitchen/cookbooks/test/metadata.rb
[ec2-user@ip-10-1-2-3 ~]$

# 21.4.413
[ec2-user@ip-10-1-2-3 ~]$ cat ~/kitchen/cookbooks/test/metadata.rb
name 'test'
version '0.0.1'
depends 'myorg_aws_chef_server_app'

depends 'hostsfile'
depends 'ssl_certificate'

```

Diff with packaged deps
![image](https://user-images.githubusercontent.com/2973273/118192539-4aab0680-b414-11eb-9621-76003c59ead8.png)

A container diff shows some difference in sizes of some of the compiled libraries.

```bash
container-diff diff chef/chefworkstation:21.4.413 chef/chefworkstation:21.4.414 --type=file
```

## Chef Workstation Version
chef/chefworkstation:21.4.414+

## Platform Version
Docker (Mac Big Sur)

**Comment by bdwyertech** [comment]
this is quite strange... berks vendor from within the container also generates empty files -- the only non-empty file is metadata.json

**Comment by bdwyertech** [comment]
The Berkshelf scratch directory looks good, it seems that the destination is what turns up empty.  Quite strange.  Stuck a couple sleep statements in, this is quite odd.

https://github.com/berkshelf/berkshelf/blob/6c7be8d7ff0a5f370490b47597e84ffbbaef3e88/lib/berkshelf/berksfile.rb#L688

**Comment by bdwyertech** [comment]
Maybe related: https://github.com/docker/for-linux/issues/1015

**Comment by i5pranay93** [comment]
@bdwyertech hey, can you please send me some of the steps that results into this issue, I am also not able to reproduce the same at my end.

**Comment by bdwyertech** [comment]
Issue has been resolved about a month ago as per my account team.  My pipes work fine now on latest images.
