### ISSUE TITLE
Chef Workstation Preferences

### ISSUE THREAD

**Issue by scottsuch** [chef/chef-workstation#2067]
## Description
- When opening Chef Workstation Preferences there are two tabs, `General` and `Advanced`. Advanced cannot be clicked. I'm assuming it's empty so maybe just remove it?

- Under the `General` tab I have `Start Workstation App on system startup` unchecked but the application does not honor this setting. It starts every time.

- The Version field is blank in the GUI when clicking on `About Chef Workstation`
<img width="535" alt="Screen Shot 2021-06-11 at 9 52 18 AM" src="https://user-images.githubusercontent.com/897179/121697101-bb3c5600-ca9a-11eb-8b4e-a9a807922e26.png">

## Chef Workstation Version
I have installed Chef Workstation via Homebrew and `brew info chef-workstation` tells me the artifact I have installed is `chef-workstation-21.6.467-1.x86_64.pkg`

## Platform Version
I'm running this on MacOS Big Sur (11.4)

**Comment by tas50** [comment]
This is fixed in the latest version of the chef-workstation-app which will ship in Chef Workstation next week. Thanks for the report.
