### ISSUE TITLE
Investigate moving `chef gem` to the go CLI

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#2154]
```
As a user I want `chef` commands to run quickly
So that I can get the information I need to do my job quickly
```

In order to make the Chef CLI as performant as possible we should investigate moving the `chef gem` command from the chef-cli Ruby app to the chef Go app. This could potentially greatly speed up this command on Windows systems.

**Comment by nikhil2611** [comment]
Hi @tas50 , just a query :
`chef gem` command right now calls the ruby library to execute its commands (like install, list etc).

https://github.com/chef/chef-cli/blob/main/lib/chef-cli/command/gem.rb#L32

This calls the `GemRunner` class and pass the arguments(or subcommands like list , install etc).
And this command implementation is done inside the ruby  library which is https://github.com/ruby/ruby/blob/v3_0_0/lib/rubygems/commands/list_command.rb

So gem is probably a ruby part and invoking the ruby library for its  implementation. We have very minimum logic in our chef-cli repo for this command.

Do we need to implement all these ruby library commands in Go now, Please suggest.

**Comment by nikhil2611** [comment]
As discussed, This should probably be in ruby always. Closing this issue.
