### ISSUE TITLE
Chef push doesn't support -p or --profile 

### ISSUE THREAD

**Issue by davsigh** [chef/chef-workstation#2266]
chef push dev-env Policyfile.lock.json -p chef-12
ERROR: invalid option: -p

Usage: chef push POLICY_GROUP [ POLICY_FILE ] [options]

`chef push` Uploads an existing Policyfile.lock.json to a Chef Infra Server, along
with all the cookbooks contained in the policy lock. The policy lock is applied
to a specific POLICY_GROUP, which is a set of nodes that share the same
run_list and cookbooks.

See our detailed README for more information:

https://docs.chef.io/policyfile/

Options:

        --chef-license ACCEPTANCE    Accept the license for this product and any contained products ('accept', 'accept-no-persist', or 'accept-silent')
    -c, --config CONFIG_FILE         Path to configuration file
    -D, --debug                      Enable stacktraces and other debug output
    -h, --help                       Show this message
    -v, --version                    Show Chef Workstation version

**If I use chef capture --help then it supports -p or --profile option.**

chef capture --help
Captures a node's state as a local chef-repo, which
can then be used to converge locally.

Usage:
  chef capture NODE-NAME [flags]

Flags:
  -s, --chef-server-url string   Chef Infra Server URL
  -k, --client-key string        Chef Infra Server API client key
  -n, --client-name string       Chef Infra Server API client name
  -c, --credentials string       credentials file (default $HOME/.chef/credentials)
  -h, --help                     help for capture
  -p, --profile string           profile to use from credentials file (default "default")
  -o, --ssl-no-verify            Do not verify SSL when connecting to Chef Infra Server (default: verify)
  -d, --with-data-bags           download all data bags as part of node capture

**Comment by tas50** [comment]
I think this is chef CLI wide except capture which is actually part of the chef-analyze go project. Knife supported profiles and the Chef CLI never did. We do need to fix this.
