### ISSUE TITLE
Stop building chef-automate-collect in chef workstation

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#2286]
## Description

We build a chef-automate-collect CLI tool for desktop product work that was put on hold. We should stop building this tool as part of workstation. We may pick the work back up at some point so let's not delete the code, but it should stop shipping / building.

**Comment by ashwin-msys** [comment]
This issue is tested. We don;t have the automate-collect in the latest build of chef-workstation. 

Please refer the SS below.
<img width="1686" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/82504775/141077231-11857194-2a23-46e2-9e08-2dd5398d0244.png">
