### ISSUE TITLE
ED25519 SSH Key support

### ISSUE THREAD

**Issue by damacus** [chef/chef-workstation#231]
## Description

ED25519 keys are not currently supported

## Chef Workstation Version

`0.1.0`

## Platform Version

MacOs 10.13

```
unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
```

**Comment by stuartpreston** [comment]
@damacus Do you mean 0.1.0? Latest stable is [0.1.150](https://downloads.chef.io/chef-workstation/stable/0.1.150).  Also can you provide a repro step?

**Comment by damacus** [comment]
Ah I just got `0.1.09` from the downloads site this morning 🤔 

Closest thing I've got to a repro is. 

- Generate key [as per this guide.](http://blog.siphos.be/2015/08/switching-openssh-to-ed25519-keys/) 
- Add key to ssh-agent
- Spin up a box using test kitchen (postgresql in this case)
  - `kitchen converge server-install-centos-7`
  - Manually place the public key in the root account of the kitchen created box.
- chef-run with a key of the type ED25519 (pretty much all of my keys are in this format)
 - `chef-run -i ~/.ssh/<key_name_here> 127.0.0.1:2200 test/cookbooks/test/recipes/server_install.rb`

**Comment by damacus** [comment]
Having the same issue with `0.1.151` or `0.1.8` (I installed 0.1.151 from t he site, but `chef-run -v` is giving 0.1.8)

For version debug reasons my chef-run binary is at `/opt/chef-workstation/bin/chef-run`

**Comment by cheeseplus** [comment]
I expect this needs to be fixed in https://github.com/inspec/train/ and it's net-ssh deps bumped.

**Comment by damacus** [comment]
Thanks! I'll take a look over there.

**Comment by cheeseplus** [comment]
I've opened a meta-issue internally trying to track all the various places that use net-ssh (so far it's knife, kitchen, and train)

**Comment by tyler-ball** [comment]
This should be fixed in the latest version of Chef Workstation (0.4.2). The underlying libraries (train-core, chef-core) got updated to add support for ed25519 keys. Please re-open this if you are still having issues!
