### ISSUE TITLE
Research: Understand current level of telemetry

### ISSUE THREAD

**Issue by skkprogress** [chef/chef-workstation#2323]
1. Which repositories have telemetry
2. Are the wirings and hooks working properly
3. Report on data being tracked at present

**Comment by nikhil2611** [comment]
This doc contains general telemetry flow and the current level of telemetry in workstation.

https://progresssoftware-my.sharepoint.com/:w:/g/personal/ngupta_progress_com/EepI1VO7wlBLu4yPQP0H1AkB1nwFiUPGkGQDV9fTk78HBg?e=NednM5

**Comment by nikhil2611** [comment]
**Which repositories have telemetry :** The only place we have telemetry in workstation is the **`chef-run`** command which is in **`chef-apply`** repo and that uses the **`chef-telemetry`** gem  : https://github.com/chef/chef-telemetry 
 
https://github.com/chef/chef-apply

It sends data to segment.io which goes to redshift and then we display it all with tableau.
`We are using a pipeline built in AWS to process incoming telemetry data. Once the data is processed it will be sent to segment and then end up in redshift for analysis.`

**Are the wirings and hooks working properly :** Yes, checked the updated data sent to segment and redshift for the **`chef-run`** command.

**Report on data being tracked at present :** chef-run command gives the timing information and data on what parameters they passed/ an action that the user has taken
Sample data:
``---
version: 1.1.6
entries:
- :event: :run
:properties:
:installation_id: 2b284412-29a9-4e8d-8507-d544c3c63b07
:run_timestamp: '2021-12-09T21:12:12Z'
:host_platform: darwin19
:event_data:
:arguments:
- :redacted
:duration: 4.765387000050396
- :event: :error
:properties:
:installation_id: 2b284412-29a9-4e8d-8507-d544c3c63b07
:run_timestamp: '2021-12-09T21:12:12Z'
:host_platform: darwin19
:event_data:
:exception:
:id: CHEFTRN007
:message: redacted
- :event: :action
:properties:
:installation_id: 2b284412-29a9-4e8d-8507-d544c3c63b07
:run_timestamp: '2021-12-09T21:12:12Z'
:host_platform: darwin19
:event_data:
:action: GenerateLocalPolicy
:target:
:platform: {}
:hostname_sha1:
:transport_type:
:duration: 4.5661639999598265
- :event: :action
:properties:
:installation_id: 2b284412-29a9-4e8d-8507-d544c3c63b07
:run_timestamp: '2021-12-09T21:12:12Z'
:host_platform: darwin19
:event_data:
:action: GenerateCookbookFromResource
:target:
:platform: {}
:hostname_sha1:
:transport_type:
:duration: 0.0008680000901222229`
