### ISSUE TITLE
Homebrew promotions failing - git auth issues

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#2325]
This script needs to be updated for main:

https://buildkite.com/chef/chef-chef-workstation-main-third-party-packages/builds/87#51b2c7cb-8f44-4cda-86a2-4be9996e4d34/101-116

**Comment by vkarve-chef** [comment]
the suggested branch reference update by rel-eng didn't help. pursuing further.

**Comment by vkarve-chef** [comment]
git authentication issue resolved by rel-eng team. now need to fix error handling in git commands.

**Comment by vkarve-chef** [comment]
updated script to conditionally commit, push changes and create PR.

**Comment by vkarve-chef** [comment]
recent [successful run](https://buildkite.com/chef/chef-chef-workstation-main-third-party-packages/builds/102#4fa39c19-2cee-40bc-9bbf-9d089edded72) that skips commit as no change detected compared to upstream
