### ISSUE TITLE
Support aix platform 

### ISSUE THREAD

**Issue by sclark007** [chef/chef-workstation#237]
Can we get some AIX love please 

## Description
CHEFTARG001

'aix' is not a supported target operating system at this time.

We plan to support a range of target operating systems,
but during this targeted beta we are constraining our efforts
to Windows and Linux.

If you are not able to resolve this issue, please contact Chef support
at beta@chef.io

## Chef Workstation Version
latest stable release 

## Platform Version
AIX

**Comment by cheeseplus** [comment]
While we may address AIX coming up, that requires an non-trivial testing setup and this is probably out of our scope for a while. What AIX versions are you looking to target?

**Comment by sclark007** [comment]
Support of the latest release will do. We are currently using 7.1

**Comment by cheeseplus** [comment]
Moved to a more appropriate repo now that `chef-apply` code has been extracted to it's own.
