### ISSUE TITLE
Workstation App missing on Windows 2019

### ISSUE THREAD

**Issue by vkarve-chef** [chef/chef-workstation#2374]
## Description
The Chef Workstation App which includes the tray icon isn't getting installed on Windows 2019. This is observed in latest stable build 21.10.640.

## Chef Workstation Version
Stable build 21.10.640.

## Platform Version
Windows 2019

**Comment by vkarve-chef** [comment]
we'll trace the build where this started happening. also will correlate with any rel-eng / packaging change for ws-app which is electron-js based.

**Comment by nikhil2611** [comment]
Related PR: https://github.com/chef/chef-workstation/pull/2402

**Comment by nikhil2611** [comment]
https://github.com/chef/chef-workstation/pull/2434
