### ISSUE TITLE
Deprecate then remove Delivery CLI

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#2378]
The legacy Delivery CLI is unmaintained Rust code that needs a significant amount of modernization in order to support Arm builds on macOS. Since 99% of this tool supports the EOL Delivery/Workflow product there's really no reason to continue shipping the tool in Workstation. We should deprecate this tool and then remove it at a future date.

## Process

- Add deprecation warning when the tool is run with a date
- Announce to Slack / Discourse
- Remove the tool
- Announce to Slack / Discourse

**Comment by vkarve-chef** [comment]
delivery CLI is removed in 22.1.778 and onwards
