### ISSUE TITLE
Current Chef RPM packages conflict with chef-workstation

### ISSUE THREAD

**Issue by bmhughes** [chef/chef-workstation#2390]
### Description

Since circa 17.4 trying to upgrade chef on a host with workstation also instaleld will fail with a file conflict.

I original posted this against [omnibus](https://github.com/chef/omnibus/issues/1037) but it's hasn't been picked up so it's probably in the wrong place.

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of chef-17.4.38-1.el8.x86_64 conflicts with file from package chef-workstation-21.9.613-1.el8.x86_64
```

### Omnibus Version

Tell us which version of Omnibus you are using

### Platform Version

- CentOS 7/8
- Fedora 34

**Comment by vkarve-chef** [comment]
@bmhughes this should now be resolved with the latest Chef Workstation version. Could you please confirm?

**Comment by bmhughes** [comment]
Yes the last couple of releases have co-existed without issue for me.

**Comment by vkarve-chef** [comment]
thanks for confirming! i'll go ahead and close this one.
