### ISSUE TITLE
Kitchen Create command got stuck when doing Chef Desktop setup

### ISSUE THREAD

**Issue by cmailank** [chef/chef-workstation#2410]
## Description
Was Setting up the cookbook for Chef Desktop usecase following Instructions from https://docs.chef.io/desktop/cookbook_repository/.
Kitchen Create command was stuck for 25 mins. Had to terminate it and move to the next section.
Note : Also, the test kitchen section on this page, says it has two virtual boxes but the kitchen.yml has 4 boxes. 

## Chef Workstation Version
21.9.613

## Platform Version
macOS 11.6

**Comment by vkarve-chef** [comment]
@cmailank could you please attach the kitchen.yml so we can diagnose further?

**Comment by cmailank** [comment]
I used the desktop-config(premium content) cookbook and here is the kitchen.yml 
https://github.com/chef/desktop-config/blob/main/kitchen.yml

**Comment by nikhil2611** [comment]
@cmailank , hey could you please  try to the run the same  `kitchen create` command again using the same `kitchen.yml` and see how much time does it take.
Please share the logs if this command  fails.

And also please let me the OS you are running this command.

**Comment by vkarve-chef** [comment]
i noticed, the mac VM that needs to be downloaded for the kitchen run is ~10GB, so that would account for the lapsed time. also, the kitchen hyperv driver would run only on Windows, unless it's a remote server specified in the config.
