### ISSUE TITLE
Notarize step is failing in release build pipeline

### ISSUE THREAD

**Issue by vkarve-chef** [chef/chef-workstation#2512]
Build is failing at the MacOS notarize step - https://buildkite.com/chef/chef-chef-workstation-main-omnibus-release/builds/1134#5381a64a-0cce-4241-b884-2e8a1cc9b750

We need to resolve this failure so that workstation build succeeds to current channel.

**Comment by nikhil2611** [comment]
This error no longer exist. I was due to the fetching of prior ws-app version which was having issue during the unzipping.
The success build for the reference-

https://buildkite.com/chef/chef-chef-workstation-main-omnibus-release/builds/1138
