### ISSUE TITLE
Update `chef generate` command for inspec content in cookbooks

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#2541]
Now that Chef Infra Client supports the compliance directory within cookbooks we want to make sure that we're generating cookbooks with the folder structure in place:

```bash
chef generate cookbook some_cookbook
```

Should have a directory like this
```
some_cookbook/
├─ compliance/
│  ├─ README.md
│  ├─ inputs/
│  ├─ profiles/
│  ├─ waivers/
```

Note: Contact PM for the readme content when this story is pulled

**Comment by vkarve-chef** [comment]
@tas50 i believe this can be closed now?
cc - @nikhil2611
