### ISSUE TITLE
Chef Workstation installs gems to a "chefdk" directory

### ISSUE THREAD

**Issue by DecoyJoe** [chef/chef-workstation#2675]
## Description
When I run `chef gem install <gem-name>` the gem gets installed to `~/.chefdk/gem/...`. This caused me a bit of confusion as I thought I had Chef Workstation installed and not ChefDK. I then started troubleshooting to see if I had some remnants leftover from my previous ChefDK installation which may have been causing gems to install to `~/.chefdk`.

I dug into the code and found the source of my confusion at [chef-workstation/omnibus/files/rubygems-customization/default/operating_system.rb:#L20](https://github.com/chef/chef-workstation/blob/main/omnibus/files/rubygems-customization/default/operating_system.rb#L20)

Looks like the project still has a number of hardcoded references to `.chefdk`.

Can we have those references updated to `.chef-workstation`? Or better yet use `::ChefUtils::Dist::Workstation::DIR_SUFFIX` from the [chef-utils gem](https://github.com/chef/chef/blob/main/chef-utils/lib/chef-utils/dist.rb#L137)?

## Chef Workstation Version
Chef Workstation version: 22.2.807

## Platform Version
macOS Big Sur

**Comment by vkarve-chef** [comment]
an upcoming current (development) release will have the fix to this issue.
