### ISSUE TITLE
macOS Ventura Compatibility

### ISSUE THREAD

**Issue by jriddle-sf** [chef/chef-workstation#2956]
## Description
Upgrading to macOS 13 (Ventura) seem to break existing Chef Workstation installation. Deleted Chef Workstation and the install cannot finish installing Chef Workstation. Reports that Chef Workstation.app is corrupted.

## Chef Workstation Version
22.10.1013

## Platform Version
MacOS 13 (Ventura)

**Comment by Stromweld** [comment]
I got this as well until i went into settings and security and allowed this app and then all that went away and the service started working again.

**Comment by kpmueller** [comment]
As Stromweld says, you have to allow the app. In order to be successful, you have to do it *before* doing the installation process, after you open the pkg file. A permission request will show up in Privacy -> Security near the bottom with an `Open App` button, or something like that.

**Comment by jriddle-sf** [comment]
I've sorted out the correct steps:

1. **Download** Chef Workstation
2. **Open** the Chef Workstation DMG file
3. **Double-Click** on the Chef Workstation `pkg` file.
4. **Click** the Allow button when the operating system says "This package will run a program to determine if the software can be installed."
5. **Click** Continue.
6. **Proceed** through the installer
7. During the installation phase you will see a warning pop-up from the operating system with a _Move to Trash_ and _Cancel_ button. Leave this window open and go to the next step.

<img width="850" alt="Screenshot 2022-10-27 at 10 25 05 AM" src="https://user-images.githubusercontent.com/85185443/198315382-59d7f11b-0ec8-451b-8d12-52e4876cbb27.png">

8. **Open** macOS Settings 
9. **Click** _Privacy and Security_ from the left-hand navigation.
10. **Scroll** down to the _Security_ section.
11. **Click** the _Open Anyway_ button.
12. **Click** _Cancel_ on the Warning window we left open above.

> **Note:** The installation will finish either way if you click this. But Chef is trying to auto-start. So clicking Cancel before then just causes the window to re-open.


Hopefully this helps all of those who got stuck on the installation due to the new Settings interface.

**Comment by vkarve-chef** [comment]
we'll anyway add a task in our backlog so we address the core issue.
