### ISSUE TITLE
chefdk got automatically updated to chef-workstation on a machine with chef yum repos configured

### ISSUE THREAD

**Issue by frezbo** [chef/chef-workstation#297]
YUM update o/p

![image](https://user-images.githubusercontent.com/18496730/47160998-bab18880-d30e-11e8-9dc3-ec380e5a9c0e.png)

Repo file:

```
~ (aws:none)(kc:none)$ cat /etc/yum.repos.d/chef-stable.repo 
[chef-stable]
name=chef-stable
baseurl=https://packages.chef.io/repos/yum/stable/el/7/$basearch/
gpgkey=https://packages.chef.io/chef.asc
gpgcheck=1
enabled=1

~ (aws:none)(kc:none)$ 

```

This completely removed `/opt/chefdk` and created `/opt/chef-workstation` and is now missing all symlinks from `/opt/chef-workstation/bin` to `/usr/bin`

**Comment by marcparadise** [comment]
This is fixed in #298 which will be released once it clears the CI pipelines.
