### ISSUE TITLE
ChefWorkstation Support for MacOS Ventura with M1 chips

### ISSUE THREAD

**Issue by OntologicalSin** [chef/chef-workstation#3019]
## Description

I could not install ChefWorkstation on a Mac computer built with an M1 chip that is running MacOS Ventura 13.1.

## Chef Workstation Version

As far as I can tell, no version of Chef Workstation supports Apple macOS 13 with an AArch64/ARM64 architecture.

## Platform Version

macOS 13 with an AArch64/ARM64 architecture.

**Comment by kmf** [comment]
Still Broken

**Comment by vkarve-chef** [comment]
we are working on resolving this issue. meanwhile, could you please navigate to System Preferences -> Security & Privacy General tab to allow the app to run? this workaround will unblock you.

**Comment by jazaval** [comment]
I'm able to install and allow the Workstation App, but it doesn't launch on Apple Silicon / Ventura.

**Comment by jazaval** [comment]
Additionally, this #2701 is a much bigger issue because bypassing the code-signing requirement requires disabling System Integrity Protection (unlike x86 Macs).
