### ISSUE TITLE
chef-workstation RPM warns of missing dependencies, probably needs refactoring

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef-workstation#345]
## Description
chef-workstation package emits scary 'missing dependency'-like text

```

Running transaction
  Installing : chef-workstation-0.2.48-1.el6.x86_64                                                                          1/1

To run the experimental Chef Workstation App, use your
platform's package manager to install these dependencies:

        libgtk-3.so.0 => not found
        libgdk-3.so.0 => not found
        libpangocairo-1.0.so.0 => not found
        libpango-1.0.so.0 => not found
        libatk-1.0.so.0 => not found
        libcairo.so.2 => not found
        libgdk_pixbuf-2.0.so.0 => not found
        libX11-xcb.so.1 => not found
        libxcb.so.1 => not found
        libXi.so.6 => not found
        libXcursor.so.1 => not found
        libXdamage.so.1 => not found
        libXrandr.so.2 => not found
        libXcomposite.so.1 => not found
        libXext.so.6 => not found
        libXfixes.so.3 => not found
        libXrender.so.1 => not found
        libX11.so.6 => not found
        libXtst.so.6 => not found
        libXss.so.1 => not found
        libgconf-2.so.4 => not found
        libasound.so.2 => not found
        libcups.so.2 => not found
        libfontconfig.so.1 => not found
You can then launch the App by running 'chef-workstation-app'.
The App will then be available in the system tray.

Thank you for installing Chef Workstation!
You can find some tips on getting started at https://chef.sh/
```

Emitting large blocks of output in the RPM %post has generally been discouraged for a long time (because the rpm tools themselves generally run unattended, and text dumped to stdout is either pointless or risky).

The missing pieces are heavily X-windows stuff.  Usually a sub-package is used to separate the X addon bits from the basic text pieces.  Then we use a system of dependencies to ensure the requirements are pulled in automatically for that X-windows sub-package (it's kinda slick -- you'll see) so the user isn't put in dependency hell (which is otherwise self-inflicted).

## Chef Workstation Version
0.2.48-1.el6  <-- el6?

If we're using the same builder or package for EL6 and others (like EL7) you should expect to cause issues.  Set up your mock or builder VMs and build it in the right environment to prevent issues.  Mock, or else careful tag generation, should get that string right.

## Platform Version
centos-release-7-6.1810.2.el7.centos.x86_64

**Comment by jonsmorrow** [comment]
Thanks for the report. The team is busy with some other priorities but I'll make sure we look at this when we get back to it.

**Comment by tyler-ball** [comment]
Hey @bby-bishopclark - you are right that this is an issue, and thank you for reporting. We made a decision in our *nix distributions to not include all the x-windows deps by default for users who wanted to install Chef Workstation on CI nodes. Our plan in the future is to produce a Chef Workstation package intended for install on user workstations (which would include the x-windows dependencies) and a separate 'Chef CI' package intended for CI/pipeline usage that would not need windowing. But thats a longer term project and is not on our roadmap yet. When we get that project added to our roadmap we will circle back to this issue.

**Comment by bby-bishopclark** [comment]
Thus the refactoring need.  When it becomes valuable again, remember that standard practice is to split optional pieces into optional packages.  It's quite seriously THE method for handling that given problem.  You'll notice it in packages like 
````
dbus-x11.x86_64 : X11-requiring add-ons for D-BUS
setools-gui.x86_64 : Policy analysis graphical tools for SELinux
net-snmp-gui.x86_64 : An interactive graphical MIB browser for SNMP
cinnamon-desktop.x86_64 : Shared code among cinnamon-session, nemo, etc
````

If a minimal bare package is valuable to the CI nodes, that simply becomes your base package, on which the optional pieces can be layered in.  It's how United did it, Open before that, and RHL before that -- but now we're going back to 1996.

I think bringing the packaging up to those standards is a good thing, but of course priorities are what they are.  Given the licensing change, and how it can potentially affect both my jobs, I'm not sure whether this will stay a priority for me; but I'll try to put some time into it if I get the ancillary details cleared and the time awarded.

**Comment by marcparadise** [comment]
I think this postinstall output is helpful if you have just a couple of missing deps, and looks like something has gone really wrong in any other case.   

I recommend that we replace that output with something like: 

```
The Chef Workstation App cannot be run because of missing dependencies. 
For more information, see https://docs.chef.io/appropriate_pre_req_link_here. 

```

I'm a little concerned with the phrasing of even that, though.  A quick skim might parse as "Workstation can't be run because of dep issues".

**Comment by marcparadise** [comment]
@bby-bishopclark I agree that separate packaging is the best way to handle this, as it would allow us to better manage these situations;  but to keep  build and distribution complexities down we're unlikely to take that approach. 

Another option that I think I like more than the message change above would be to generate a first-run wrapper around the App on linux.  That wrapper could then check pre-reqs and recommend a package to install to enable it.

**Comment by bby-bishopclark** [comment]
>  to keep build 
The build process is still rpmbuild -ba .

> and distribution complexities down
The yum repo is configured identically.

> generate a first-run wrapper 

This threatens the single source of truth that's inherent and crucial to a sane Enterprise system.  If the package still installs atomically without this OOB script killing it halfway-through - which is a fine mess - then the OOB script usurps authority over dependencies and installation state.  Loan sharks could beat the rate which which this technical debt will accumulate, all for the reluctance to create a sub-package like we've done since last millennium.

But that's why it's best practice to do it properly.  Your wallet, your decision.
