### ISSUE TITLE
chef-workstation RPM doesn't set PATH properly

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef-workstation#346]
## Description
Binary locations aren't added to the 

```
[root@localhost ~]# yum install chef-workstation -y
[root@localhost ~]# bash -login
[root@localhost ~]# which irb
/usr/bin/which: no irb in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin)
```

Normally it's as simple as dropping a file in as /etc/profile.d/chef-workstation.sh:
```
::::::::::::::
/etc/profile.d/chef-workstation.sh
::::::::::::::
export PATH=$PATH:/opt/chef-workstation/embedded/bin
```
There are some concerns about precedence, and about a dozen ways to solve that; some of them effective.  But if we run into that problem, we're already a step further than we are now.

## Chef Workstation Version
chef-workstation-0.2.48-1.el6.x86_64

## Platform Version
centos-release-7-6.1810.2.el7.centos.x86_64

**Comment by jonsmorrow** [comment]
@bby-bishopclark Thanks for reporting this but it is behaving as designed. During install we generally don't put embedded bins on the path because we don't want to take over your shell. We provide `chef shell-init` which will add everything to the path and take over the shell if that's desired.
