### ISSUE TITLE
Specify Chef Client installer location

### ISSUE THREAD

**Issue by lavahot** [chef/chef-workstation#355]
## Description
Having a config option in the config.toml file to specify the network location of the chef client installer would greatly cut down on the network overhead for bootstrapping our environments. As it is now each client must first download the chef client from the internet which takes significantly longer than using our network source.

## Chef Workstation Version
0.2.48

## Platform Version
Windows 10

**Comment by jonsmorrow** [comment]
@lavahot Can you provide us a little more context. Are you using chef-run here? Is the expected behavior that your workstation would pull the installer from a network location or the target?

**Comment by lavahot** [comment]
Sure. I'm using chef-run. The behavior I'm expecting is that the target
pulls the client from a network location. I mean, I'm assuming that as-is
the target pulls the client via omnitruck method (or otherwise pulls it
from the Internet).

**Comment by jonsmorrow** [comment]
@lavahot  currently chef-run pulls the artifact via omnitruck to your workstation and caches it there. On first run of a target the artifact is uploaded from your workstation to the target.

**Comment by lavahot** [comment]
Ohhhhhhhhhh. Well then having a cached version available to a private network is a bit useless then. Please disregard.
