### ISSUE TITLE
Chef Workstation 2.53.1 on Windows pathing bug

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef-workstation#365]
## Description
Start-chefws.ps1 fails to start properly. It throws the following error: 

```
Import-Module : The specified module 'chef' was not loaded because no valid module file was found in any module directory.
At line:1 char:133
+ ... l | out-string | iex; Import-Module chef -DisableNameChecking;echo 'P ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (chef:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

In reviewing the script and the locations of the both the script and the module it's calling, the script is incorrectly locating the module and script roots. if the path is correctly specified, the chef.psm1 file loads correctly even though it has warnings itself. 

## Chef Workstation Version
2.53.1

## Platform Version
Windows 10. Build 1809

**Comment by jonsmorrow** [comment]
@johnmccrae Thanks. We'll take a look at this in the coming weeks.

**Comment by jonsmorrow** [comment]
We need to confirm the issue.

**Comment by afiune** [comment]
I think we have already fixed this problem with https://github.com/chef/chef-workstation/pull/482

Testing the powershell script in the latest version of Chef Workstation works just fine:

![Screen Shot 2019-11-06 at 2 24 07 PM](https://user-images.githubusercontent.com/5712253/68339244-6c9a2f00-00a1-11ea-8a14-d8fcc886a4b6.png)
