### ISSUE TITLE
Create chef-workstation Docker Image

### ISSUE THREAD

**Issue by mbaitelman** [chef/chef-workstation#374]
Currently there is a chefdk docker image https://hub.docker.com/r/chef/chefdk/
As DK is being replaced by workstation would it be helpful to create a new image for users to use that will be kept up to date?

The current image works fine but this would make things clearer for users going forward.

**Comment by tas50** [comment]
We absolutely should do this. Thanks for the reminder.

**Comment by mbaitelman** [comment]
Is this the new image? https://hub.docker.com/r/chef/chefworkstation

**Comment by mbaitelman** [comment]
New image created.
