### ISSUE TITLE
Ship habitat in Workstation

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#421]
### Describe the Enhancement:
Ship the hab binary in Workstation
Every stable release of `hab` opens a PR to include this update in Chef Workstation
Users running `chef shell-init` will get the `hab` binary on their path from the CW package before any other installs of hab (EG, homebrew managed hab)
Update the docs to add a dependency on Docker for MacOS hab users

### Describe the Need:
Workstation is the single tool for being successful with Chef Software products. Right now it ships with Infra and InSpec tools. It currently lacks tools for Habitat.

### Current Alternative
A user must download both Workstation and Habitat

### Can We Help You Implement This?:
Add it to the package

**Comment by sam1el** [comment]
Workstation should also be able to generate an "effortless" package for either inspec or cookbooks. Having hab as part of the whole suite for development makes sense

**Comment by afiune** [comment]
The only limitation or problem I see with packaging habitat in Workstation is the case where we start installing Workstation as a Habitat package instead of an omnibus package. (long term dream)

You would use Habitat to package Workstation that itself contains Habitat. How would you install Workstation? (`Habitat -> Workstation -> Habitat`)

![tenor-237932211](https://user-images.githubusercontent.com/5712253/62620316-4f768880-b919-11e9-80c1-42ed0f6a67d1.gif)

**Comment by jonsmorrow** [comment]
For this implementation we wont worry about cleaning up the /hab dir on uninstall.

**Comment by tyler-ball** [comment]
No, we do not intend to include Docker inside Workstation. Hab already has a message if docker isn't installed:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
✗✗✗
✗✗✗ The Docker image habitat/default-studio-x86_64-linux:1.6.39 is unreachable due to a network error.
✗✗✗ The image must be reachable to ensure the versions of hab inside and outside the studio match.
✗✗✗ You can specify your own Docker image using the HAB_DOCKER_STUDIO_IMAGE environment variable.
✗✗✗
```

**Comment by tyler-ball** [comment]
Question we need to answer: how would we leverage omnibus to include `hab`? Would we download and include pre-built `hab` binaries, or would we build `hab` from source, or do something else?
