### ISSUE TITLE
Customers have a list of work required to upgrade their cookbooks to latest version of Chef Infra Client

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#442]
## What problem are we solving?

Upgrading from older versions of Chef Infra Client to Chef Infra Client 15.X takes work. Customers need to know what that work is in order to do it. We want to help customers answer the question of "how much effort do I need to put in to get to the latest version of Chef infra?"

Facilitating successful customer transitions from older chef client version to current versions and patterns with minimal friction. This epic is primarily targeting our internal CS teams but needs to have sufficient integrity such that an actual customer can use this as well.

## Objective and Key Results

**Objective** | **Key Results**
-|-
Provide some tool that allows customers to get a report about the current version of chef infra they are on.
\\
Goal is to migrate all customers onto effortless in the next 2 years|- Feedback from the field that migration process is easier
- Migration tools are used by 80% of CS teams by 1H 2020

## Deliverables

- Tool that will produce a list that maps Chef infra version to platform count (e.g. list indicates which version each node is on)

    - Connect to a chef server and read every node object producing a report showing the number of nodes on each chef infra client version split by os family. (see example below)

![](https://chef.aha.io/attachments/6735454055486010555/token/653a52a71a09430614a4b029a874659e436c67a8eed191c1ed2fba6d9f183139.download?size=original)

- Look at the run lists on each of these nodes and download whatever cookbooks are used and run them through cookstyle reporting on deprecations and usage patterns that are incompatible with the effortless pattern. This report would show all the things that need to be fixed grouped by cookbook giving a clear picture of how much real work needs to be done. Leverage cookstyle to detect what needs to be deprecated and a report of what can be fixed automatically and what needs to fixed manually.
- Produce a set of cookstyle rules covering all the food critic rules and coding patterns that will break under Chef 15 or effortless. Output will be a report.

## Evidence

- tbd

## Dependencies

- Partially dependent on WS-E-17. (Can't complete this epic fully until 17 is completed. Can still do partial features)
- UX team support to map out interactions w/ tools and report outputs. (will reach to UX team and discuss how support)
- Doc team support to create/review documentation (will reach to Doc team and discuss how to support)
- Since we are unable to replicated 100% of the customer's EN, we can't have 100% certainty that our reports would capture everything that needs to be fixed.

## Assumption

- When applying the results from this epic at the customer site, there is a Chef server existing and the person running the tool has sufficient access to list the nodes and download cookbooks for the Chef server Org. Depending on the credentials that the person using the tool has, they may be limited to some but not all of the Chef server Orgs in their company.
- Even w/ the report that we generate, there may be additional fixes required that are specific to the customer's SDLC pipeline that they would need to fix on their own.

## Acceptance Criteria

- Cookstyle is in a state that supports this epic. (A minimun amount of rules to help users upgrade to Chef Infra 15)
- A command exists that can target every node and be run to do the activities in this epic
- A machine readable report is generated in the end (e.g. JSON)
- A human readable report is generated in the end (e.g. txt)
- Documentation somewhere on how to use this

## Out of Scope

- Customers w/o Chef server will not be covered by this epic
- This will not work for customer w/ Chef zero (e.g. running Chef w/o Chef server)

## Open Questions

1. Need to confirm from the field, do customer have centralized teams that has access to all Chef Orgs or do they have decentralized teams where they have access to some but not all Chef server Orgs. How can we no when to turn off the old Chef stuff?
2. Can we leverage Automate for information that we can't get from the Chef server?
3. With cookstyle and Rubocop (CLI), how much confidence do we have on accurately reporting on what can be automatically fixed and what needs manual fixing.

## Reference Docs

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6735454055486010555" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>pasted image 0.png (https://chef.aha.io/attachments/6735454055486010555/token/653a52a71a09430614a4b029a874659e436c67a8eed191c1ed2fba6d9f183139.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://chef.aha.io/epics/WS-E-16

**Comment by afiune** [comment]
Summary: From a list of inventory how do we get them to "the final state" (define that state)

Things we know we need to report:
1) Upgrade the client version
2) Upgrade cookbooks to work with the latest client version
3) What else?

Scope:
* Being able to point to a fleet of nodes, a single node or all the nodes. (Support Knife search style)
* Only customers that have a Chef Server.

Out-of-Scope:
* Not going all the way to effortless. (cover on a next epic/task)

Things we need to know about the customer's infrastructure:
* Total number of nodes with chef client version and run list
* A way to get the cookbooks to be able to run cookstyle and understand the state
* Last time of check-in of nodes and if they have succeeded chef-client run or not.

Open Questions:
1) Are we covering customers without Chef Servers? If yes, how do we gather the information above?
2) What format do we present the report?
*) Text? Json? Pdf?
3) Is the "final state" go all the way to use the effortless pattern? Or just update everything we can, meaning go to the latest versions of cookbooks and chef tools.?
4) With cookstyle and rubocop: How much can we correct and predict? How much is missing to have a decent deliverable? How much can we report but not correct automatically? (Knowns/Unknowns)
5) Blind spots? Custom scripting that customers might have to control/manage their infrastructure. Is there a way to verify that after the upgrade such scripts will continue to work?
6) Can we leverage Automate as the source of truth? But what if customers don't have an Automate server?

**Comment by afiune** [comment]
MVP Proposal: Have access to a Chef Server and give an overall report of all out-of-date nodes and all cookbooks that need to be fixed/updated with a percentage of how much can we automatically fix with our tooling.

**Comment by jonsmorrow** [comment]
Comment added by Tyler Ball in Aha! - [View](https://chef.aha.io/comments/6737309074405586994)

Required cards: documentation of topologies we are going to target, repeatable method for creating and destroying that topology

**Comment by tyler-ball** [comment]
UX and product have requested that one of the outputs of data be CSV so they can more easily analyze the data. I propose there are two reports we generate. The first is an 'inventory' of nodes and cookbooks that can be referenced again in the future to *potentially* disect in different ways. This allows users to answer questions like "how many nodes in my test environment need to be updated" or "how many cookbooks on my Windows nodes need to be fixed". 

The second report would be the more immediate answer of "what is wrong with my cookbooks". This is a list of the cookbooks deployed across their infrastructure, the versions of those cookbooks being ran, the cookstyle rules violated for each cookbook/version, and what rules we can automatically fix for them.

The first report would be used internally to keep developing this tool and the second report would be used by customers to help identify cookbooks they need to update.

**Comment by afiune** [comment]
We have successfully completed the requirements on this epic, all the things that were
attached to the epic have been moved to the [chef-analyze report refinements](https://github.com/chef/chef-workstation/issues/884)
