### ISSUE TITLE
Cookbook generator issue that could be a gem issue?

### ISSUE THREAD

**Issue by bnwoods** [chef/chef-workstation#449]
## Description
We are using a  gem in place of the built in cookbook generator. Upon updating to v0.8.7 (actually installs as version 1.0.11) it no longer respects the custom generator and just uses the built in one. As part of this, the gem is installed directly into `/opt/chef-workstation/embedded/bin/gem` and there is the following defined in our knife.rb:

``` ruby
if defined?(ChefDK::CLI)
    require 'chef_gen/flavors'
    chefdk.generator_cookbook = ChefGen::Flavors.path
end
```

If feels like Chef Workstation has stopped respecting the override in the knife.rb and is just going to the built in generator. 

Speculation in the Chef Success slack is that this might have something to do with the gem changes and the removal of the chefdk dependency. 

This works on Chef Workstation 0.7.4 and previous.

Slack Conversation Starts Here: https://chef-success.slack.com/archives/C0YQPNWAG/p1566830886003900

To test, our gem is based on the [pan gem made by echohack](https://github.com/echohack/pan). We've modified ours, but it still works under the same basic concept. 

## Chef Workstation Version
0.8.7 (Which installs 1.0.11 on Mac from downloads.chef.io)

## Platform Version
Mac OSX Mojave 10.14.1 (18B75)

Aha! Link: https://chef.aha.io/features/SH-2569

**Comment by tas50** [comment]
I'm working on a cookstyle rule for this to autocorrect to the new format

**Comment by bnwoods** [comment]
Thank you @tas50!
