### ISSUE TITLE
Release notes from a current build don't work

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#490]
## Description
From the about dialog if you click release notes you get an error if you're on a current build. There will never be a notes for a current release and the URL will always point to stable.  For example this is 0.9.19 (current):

https://packages.chef.io/release-notes/stable/chef-workstation/0.9.19.md

## Chef Workstation Version
0.9.19

## Platform Version
All

**Comment by tyler-ball** [comment]
The error message this displays is nasty. We *probably* won't be able to display release notes for a current channel release in any case, but we could at least make this error better (or grey out the button if the URL it would access raises a 4xx?)

**Comment by tyler-ball** [comment]
Closing this and moving work on it to https://github.com/chef/chef-workstation-app/issues/163
