### ISSUE TITLE
buster package for chefdk

### ISSUE THREAD

**Issue by arthurlogilab** [chef/chef-workstation#520]
Not sure this is the right project to file this issue, feel free to show me where to report this. 

https://downloads.chef.io/chefdk only shows packages for debian stretch 9 (oldstable) and jessie 8 (oldoldstable), both which have LTS (long term support) so that's great. 

The current stable is debian buster 10 (stable), it would be nice to have a debian package for this version of debian.

**Comment by tyler-ball** [comment]
Moving to Chef Workstation since that is where development is occurring. We are unlikely to add a Buster package for ChefDK but we should get one added for Chef Workstation. Thank you for the report!

Lets confirm with Release Engineering that we have pipelines for this.

**Comment by tyler-ball** [comment]
I also think this is a good candidate for the Sustaining team, but I need to go investigate the process to get this added to their work queue.

**Comment by tas50** [comment]
We have a Debian 10 package at this point. Closing this.
