### ISSUE TITLE
Rename the `chef` binary to `chef-cli`

### ISSUE THREAD

**Issue by afiune** [chef/chef-workstation#538]
Originated from https://github.com/chef/chef-workstation/issues/497: We need to make space for a new `chef` top-level wrapper that calls all our sub-binaries.

## Motivation
As a Chef developer,
I would like to have the `chef` command available to use,
so that I can create a top-level wrapper that calls all our sub-binaries.

## Specification

- Rename the `bin/chef` to be called `bin/chef-cli`.
- Update the `chef-cli.gemspec` executable.
- Make a major version bump for the chef-cli gem.

Three changes ☝️ above https://github.com/chef/chef-cli/pull/35
- Update the post script's (unix & windows) in chef-workstation to link the new binary name. https://github.com/chef/chef-workstation/pull/551
- Symlink `chef` to `chef-cli` until the new `chef` command is ready to be pulled in. https://github.com/chef/chef-workstation/pull/551

## Downstream Impact

- Chef DK
- Chef Workstation

## Work in progress
https://github.com/chef/chef-cli/pull/35

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-cli/pull/35
