### ISSUE TITLE
ChefDk Version 2.4.17 Powershell Error when Initializing

### ISSUE THREAD

**Issue by omar-irizarry** [chef/chef-workstation#543]
# Description

When Starting Chef Development Kit the following error is thrown:
```
Cannot run a document in the middle of a pipeline: C:\windows\system32\Out-String.
At line:1 char:105
+ ... v:CHEFDK_ENV_FIX = 1; chef shell-init powershell | out-string | iex;  ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\windows\system32\Out-String:String) [], Run
   timeException
    + FullyQualifiedErrorId : CantActivateDocumentInPipeline

PowerShell 5.1.14409.1005 (Microsoft Windows NT 6.1.7601 Service Pack 1)
Ohai, welcome to ChefDK!
```
By modifying the following line in Start-chefdk.ps1 from
`chefdkinit = '"$env:PATH = ''' + $chefdk_bin + ';'' + $env:PATH; $env:CHEFDK_ENV_FIX = 1; chef shell-init powershell | out-string | iex; Import-Module chef -DisableNameChecking"'`
to
`$chefdkinit = '"$env:PATH = ''' + $chefdk_bin + ';'' + $env:PATH; $env:CHEFDK_ENV_FIX = 1; chef shell-init powershell | iex; Import-Module chef -DisableNameChecking"'`
The error is no longer thrown, and the Path environment variable has the following additional entries:
```
C:/opscode/chefdk/bin
C:/Users/username/AppData/Local/chefdk/gem/ruby/2.4.0/bin
C:/opscode/chefdk/embedded/bin
C:/opscode/chefdk/embedded/git/usr/bin

```
# ChefDK Version

Chef Development Kit Version: 2.4.17

# Platform Version

Windows 7 Enterprise (Build 7601: Service Pack 1)
Chef Version
```
PS C:\> chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.45.13
```

Powershell Version
```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

# Replication Case
Launch Chef Development Kit.

# Stacktrace

```
Cannot run a document in the middle of a pipeline: C:\windows\system32\Out-String.
At line:1 char:105
+ ... v:CHEFDK_ENV_FIX = 1; chef shell-init powershell | out-string | iex;  ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\windows\system32\Out-String:String) [], Run
   timeException
    + FullyQualifiedErrorId : CantActivateDocumentInPipeline
```

## NOTE: CHEFDK BUGS ONLY

This issue tracker is for the code contained within this repo -- `chefdk`.

- [Server issues](https://github.com/chef/chef-server/issues/new)
- [Chef-client issues](https://github.com/chef/chef/issues/new)
- Cookbook Issues (see the <https://github.com/chef-cookbooks> repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by tyler-ball** [comment]
Thanks for the throughouly documented issue @omar-irizarry. I need to go test this with the latest version of Chef Workstation because it still has the `out-string` in the command. I have not seen this error before but we do our testing on Windows Server so perhaps Windows 7 has a different issue. Maybe Powershell 5 doesn't support `out-string`? https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-string?view=powershell-6&viewFallbackFrom=powershell-5 seems to indicate so but it isn't super clear

**Comment by tas50** [comment]
I'm going to close this out at this point since we haven't heard back from you @omar-irizarry. If you're still having this problem please do let us know by opening the issue back up with new output from chef-workstation.
