### ISSUE TITLE
Please do NOT drop foodcritic from workstation for at least 1 year after deprecation

### ISSUE THREAD

**Issue by jaymzh** [chef/chef-workstation#560]
In [this blog post](https://blog.chef.io/goodbye-foodcritic/), Chef announces the deprecation of Foodcritic in favor of cookstyle. In last week's Developer meeting, @tas50 mentioned that the plan was to not include FC in the April release of Chef Workstation. However, lost of people have complicated rules that need to be converted to cookstyle, or in some cases cannot be converted. Some of these rules are incredibly complex xpath that will take time. Further, there is, as of yet, no documentation on how to do common FC-like things with cookstyle.

So per today's Chef Developer Meeting I'm filing a request here for:

1. Please do not drop FC until April 2021 (i.e. the Chef 17-coupled release) to give people time to migrate rules
2. Please provide documentation for FC method replacements where applicable. Some examples:
    * There are helpers in FC to get a list of actions or a list of properties on resource - how to do this in cookstyle
    * Resources for cookbook metadata info ("this recipe uses this thing, but is it depending on the cookbook that provides this thing"?)
    * List of things that are **not** possible to do in cookstyle that were common in FC to prevent people wasting lots of time trying (knowing all node methods, looking at all recipes in a given cookbook together, etc.)

The date above assumes that the docs are wrapped up before April 2020 - the goal there is that once the docs exist, people should have another full Chef release to migrate.

To alleviate @tas50 's support concern, I think it's fine to drop *support* of FC in April 2020, as long as FC is still available in WS and passes the basic smoke test (i.e. if WS wants to use incompatible libraries, that's the only sort of change I'd expect to fall on Chef Inc. to fix... otherwise bugs and feature requests would fall on the community).

Thanks!

**Comment by robbkidd** [comment]
I ask the following with the goal of understanding alternatives, how they may or may not meet needs, and therefore shaping the decision around continuing to include foodcritic and what level of support to expect.

Were foodcritic removed from Workstation in April 2020, could an install of Workstation plus a post install `chef gem install foodcritic` support FC usage after that date?

**Comment by jaymzh** [comment]
Hey @robbkidd - good question, happy to answer.

The short answer is no, and I'm happy to elaborate.

There's several issues with this.

The first and foremost is that this will in no way ensure that the gem set FC uses and the gem set that WS uses are compatible.

But there's also significant technical issues with that approach.

Obviously making people manually setup their development environment isn't reasonable so we use Chef to do it. I'm not a huge fan of changing user stuff using chef, but let's assume we wanted to do that... `chef gem install` will install into a homedirectory... which in many cases is an NFS directory... which, at least in FB's case and certainly in other cases as well, requires a krb5 ticket to mount, so Chef can't just do this for users. Plus iterating over users and running stuff that affects their homedir is ... pretty ugly.

You could, instead force an install as root and into `/opt/chef-workstation`, but that's even worse, then you end up making the RPM/Deb un-upgradable without significant acrobatics.

And of course remember that you need to do this for all contributors to Chef, which in an organization practising devops is going to be nearly every developer and nearly every SA/SRE/PE... so expecting everyone to go down some wiki page of commands to run to setup their environment is not remotely scalable.

BTW this is a more detailed version of the same case I laid out in https://github.com/chef/chef-workstation/issues/541 . I'm always happy to explain the use cases, but it is a little surprising that automated setup of development environments doesn't seem to be a first-class assumption.

I hope this helps explain.

**Comment by tyler-ball** [comment]
We're going to work with the product team on how to best address your concerns as well as iterating on Chef Workstation to deprecate and replace old software.

**Comment by tas50** [comment]
The next release of Workstation will drop Foodcritic. Sept 2019 - Nov 2020.
