### ISSUE TITLE
[Proposal] Feature Flags

### ISSUE THREAD

**Issue by afiune** [chef/chef-workstation#609]
## Motivation
    As a Chef Workstation user,
    I would like to enable features on my local workstation,
    so I can safely test functionality that has not been yet released (BETA).

    As a Chef Workstation developer,
    I would like to be able to release new features behind a flag (feature flag),
    so I can safely ship new functionality (BETA) without breaking users.

## Specification
With the new architecture that we have in Workstation, that is, small modular
binaries and the `chef` top-level command, we need to standardize how are
we going to add Feature Flags across our ecosystem.

Components that we must cover:
1. Chef Workstation App
1. `chef` top-level command
1. Any other CLI binary (ex. `chef-analyze`)
1. (Question) Are we covering other components like `chef-run`, etc.?

The proposal is to have three places where users can **enable features**:
1. Environment variables: `CHEF_FEAT_[FOO]=true`
1. Configuration file: `$HOME/.chef-workstation/config.toml`
    ```
    [features]
    foo = true
    ```
1. (vision-to-the-future) Through a UI coming from our Chef Workstation App:
    ☑️ All Features
    ☑️ Foo Feature
    ☑️ Bar Feature

This could be done in a new Go package called `featflag` that works as a library
for other CLIs (for example, `chef-analyze` or even the top-level `chef` wrapper),
such package should have the following capabilities:

- Define a Go type that represents a Feature Flag. (suggested name `Feature`)
- Define a list of features that are global and accessible out-of-the-box.
- Be able to add new features to the existing global list.
- Have an accessor `Enabled()` that returns whether or not the feature is enabled.
- Define a generic and global Feature Flag to turn all features at once. (`CHEF_FEAT_ALL`)
- List of features with the description of what they do plus if they are turned on or off.

## Downstream Impact

Mostly the entire Chef-Workstation realm.
(Which includes the following [list of repositories](https://github.com/chef/chef-oss-practices/blob/master/projects/chef-workstation.md#project-repositories)).

**Comment by afiune** [comment]
Moving on to implement the first pass of this proposal, I will start with the `featflag` Go package.

**Comment by marcparadise** [comment]
If instead of `Enabled()` we did `Available()`, this would let us also verify that the feature is available in the local build, so that we do not allow something to be enabled that is not part of the package.

**Comment by tas50** [comment]
👍

**Comment by afiune** [comment]
@marcparadise thanks for your suggestion, this proposal implements a go package
to manage the feature flags across our ecosystem but, it is not the source of truth
from every single feature we package, I think that one way to do this is through the
Chef Workstation App https://github.com/chef/chef-workstation-app/pull/125 where
we will have a real list of things a user can enable within the installed package.

<img width="538" alt="Screen Shot 2019-11-08 at 1 40 26 AM" src="https://user-images.githubusercontent.com/5712253/68744429-d9d22680-05b1-11ea-9d83-30d07dcd2155.png">

What do you think about that idea?

**Comment by afiune** [comment]
This proposal is now implemented, there are two things missing that will be tracked
at https://github.com/chef/chef-workstation/issues/724 

The two final PRs that is closing this Issue are:
* https://github.com/chef/chef-analyze/pull/74
* https://github.com/chef/chef-workstation/pull/711

![tenor-173629477.gif](https://images.zenhubusercontent.com/5d24c5fece2ee57f46f4f7b5/c1c004fa-c36a-47bb-8d6d-70875c67b9f9)
