### ISSUE TITLE
Bug using test-kitchen + Policyfiles on Windows

### ISSUE THREAD

**Issue by afiune** [chef/chef-workstation#633]
## Description
Chef-Workstation Upgrade from `0.9.42` to the latest stable release (today) `0.10.41` doesn't
allow users to use. Any `kitchen` command will fail with the output:
```
!!!!!! The `chef` executable cannot be found in your PATH. Ensure you have installed
ChefDK or Chef Workstation from https://downloads.chef.io and that your PATH setting
includes the path to the `chef` command.
```

## Chef Workstation Version
Chef Workstation `0.10.41`

## Platform Version
Windows Systems

## Replicate this Bug

- Install the Chef Workstation `v.0.10.41`
- On a Powershell terminal:
    - Initialize a kitchen config `kitchen init`
    - Create a Policyfile `chef generate policyfile`
    - Try to list the Instances `kitchen list`

**Comment by sam1el** [comment]
Did some testing on this with users this morning to further confirm some suspicions. If there is a policyfile folder with a policyfile.rb in it, no error. If there's a policyfile.rb in the top level where the kitchen.yml resides. the errors happens every time.
