### ISSUE TITLE
Not able to generate chef cookbook

### ISSUE THREAD

**Issue by anwarshadab01** [chef/chef-workstation#637]
> >> You must enter 'yes' or 'no'
> >> You must enter 'yes' or 'no'
> >> You must enter 'yes' or 'no'
> >> You must enter 'yes' or 'no' 
........
The above message continuously blinks on my AWS linux terminal when i try to create Chef cookbook
Commands i use after installing chef
#wget https://packages.chef.io/files/stable/chef-workstation/0.10.41/el/7/chef-workstation-0.10.41-1.el7.x86_64.rpm
#yum install chef-workstation-0.10.41-1.el7.x86_64.rpm -y
#mkdir cookbooks (Creating cookbooks directory)
#cd cookbooks (Entering into that directory)
#chef generate cookbook test-cookbook (generating cookbook)
I have installed Red Hat Enterprise Linux 7 workstation
I am not even able to enter "Yes" because it blinks continusouly and fills my whole terminal.

**Comment by tyler-ball** [comment]
Thanks for the report @anwarshadab01 - can you confirm that above that blinking prompt it is asking you to accept the Chef license? The prompt is supposed to appear and stay until a user responds to it, not repeat over and over.

To get around this while we fix the bug you should be able to pass `--chef-license accept` to your `chef generate` command.

**Comment by afiune** [comment]
I have just confirmed that this is a critical issue, we are not even able to interact
with any command like `chef exec irb`. I'm going to prioritize it to start working on it!

**Comment by afiune** [comment]
@anwarshadab01 Even though this issue has been closed, please wait for a new Chef Workstation release, the issue that tracks that work is: https://github.com/chef/chef-workstation/issues/652

**Comment by anwarshadab01** [comment]
@tyler-ball You are correct , the blinking continues for 60 seconds and takes  no input from the  user. It works well when the first command on chef is run with **--chef-license accept**.
