### ISSUE TITLE
My local cookbooks are not being resolved

### ISSUE THREAD

**Issue by francoisfaubert** [chef/chef-workstation#665]
## Description
I am building a list of cookbooks that will be inter-referencing each other under the same parent working directory. Using the CLI, I cannot resolve neighboring local cookbooks. 

I am unsure if it comes from a misunderstanding of how the tool works with or without `--cookbook-repo-paths` or if it is a real issue.

## Chef Workstation Version
chef-run: 0.1.21

## Platform Version
Windows 10, 64bit

### File details
Here is the file structure of my project, with many of the generated files omitted (it's on another drive than my user directory).
```
E:\Projects\mycompany\dev-ops\tests\chef-example
├───cicd
│   ├───recipes
│   ├───templates
│   └    metadata.rb
└───mycompany_docker
    ├───recipes
    └    metadata.rb
```
In the metadata.rb files, 'cicd' has a `depends 'mycompany_docker'` and that one's metadata.rb has a `depends 'docker'`.  I have double checked the value of the `name` attribute. 

Both cookbooks run correctly if I run them without that dependency.

### Failing command
`chef-run me@mydomain --cookbook-repo-paths E:\Projects\mycompany\dev-ops\tests\chef-example cicd`

### Partial Trace
```
Caused by: Solve::Errors::NoSolutionError: Unable to satisfy the following requirements:
- `mycompany_docker (>= 0.0.0)` required by `cicd-0.1.0`
```

Hopefully this is not something I missed in the documentation.

**Comment by afiune** [comment]
Thank you for taking the time to file this issue. Unfortunately, this is not something we can address at this time due to resource constraints and a workaround already exists.
