### ISSUE TITLE
Replace chef-apply with chef-run

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation#686]
chef-run was scheduled to be renamed to chef-apply.  Let's either do this, or fix the namespacing of the chef-run command to be ChefRun and not ChefApply.

Aha! Link: https://chef.aha.io/features/SH-1746

**Comment by tyler-ball** [comment]
We originally wanted to replace the functionality of `chef apply` with the chef-run functionality but wanted to wait until a major version rev to change this behavior for users

**Comment by tyler-ball** [comment]
There is existing getting-started documentation that refers to `chef apply` as an easy way to execute cookbooks locally. We'll want to update that documentation and add a local-mode execution to `chef-run` so users do not lose functionality
