### ISSUE TITLE
Foodcritic going away warning message in CLI

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#697]
## What problem are we solving?

In preparation for Foodcritic EOL planned for Apr 2020, the desire is to provide a warning message in Workstation to let user know in advance.

## Objective and Key Results

**Objective** | **Key Results**
-|-
- Users of Foodcritic are made aware of its EOL and are informed/suggested to use cookstyle
- Users concerned w/ Foodcritic going away are provided w/ a channel to provide feedback (e.g. github link?)|- Foodcritic users switch to cookstyle
- Foodcritic users concerned w/ EOL contact us via the appropriate channels

## Deliverables

- See image for mockup.

![](https://chef.aha.io/attachments/6756308810165436721/token/b2ad54eae279f5c12678d5a110f290e6ccaf059212ab43aaca6a88a464050c54.download?size=original)

**Text Copy:**

See attachment

## Evidence

- TBD

## Dependencies

- TBD

## Assumption

- TBD

## Acceptance Criteria

- TBD

## Out of Scope

- TBD

## Open Questions

1. TBD

## Reference Docs

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6756308810165436721" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screen Shot 2019-11-06 at 1.01.31 PM.png (https://chef.aha.io/attachments/6756308810165436721/token/b2ad54eae279f5c12678d5a110f290e6ccaf059212ab43aaca6a88a464050c54.download?size=original)

<span data-href="#aha_attachment_6756309598919098709" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>FC EOL warning text (https://chef.aha.io/attachments/6756309598919098709/token/0b8c1081be78a5aaed90192e60252ea7d72c7d43ea6af29df59fcca704478dc5.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://chef.aha.io/epics/WS-E-23

**Comment by tyler-ball** [comment]
How do we ensure we output a deprecation message in the output if users programmatically parse the output of FC? We don't want to break their CI system.

For now we are only going to change the output of the help text.
