### ISSUE TITLE
List feature flags that users can activate

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#709]
### Describe the Enhancement:
As a user of Chef Workstation,
I want a list of feature flags available and descriptions for each,
so that I know what beta features I can opt into.

### Describe the Need:
https://github.com/chef/chef-workstation-app/pull/125 handles this really well via the UI (and an enhancement I would make there is to have a description for each feature flag). But for non-app users I would like a way for them to know what feature flags they can enable and how.

I would tentatively suggest a `chef list feature-flag` command:

```
$ chef list feature-flag
Feature flags that can be enabled for the Chef Workstation ecosystem. Set the following environment variables to any value to enable flags:

* CHEF_FEAT_ALL - environment variable to enable all possible feature flags
* CHEF_FEAT_ANALYZE - enable the `chef-analyze` command

Or add the following configuration to your `~/.chef-workstation/config.toml`:

[features]
# enable all possible feature flags
all = true
# enable the `chef-analyze` command
analyze = true
```

### Current Alternative
N/A

### Implementation notes
One idea Salim and I discussed was creating a golang library that knows about feature flags and how to enable them, that also exposes a non-user-oriented binary. This would enable all our tools (Golang, Ruby, Javascript) to toggle feature flags using one single library.

**Comment by afiune** [comment]
While doing triage we talked briefly about the situation where we will add and remove
features and how do we want that to be consistent with the Chef Workstation App and
this new command. This work needs some design proposal to think about config files
and something that can be leveraged across the entire Chef Workstation ecosystem.

**Comment by tyler-ball** [comment]
https://github.com/chef/chef-workstation-app/pull/125 implements a UI based approach for toggling feature flags. Since we don't have any current plans to create a CLI based approach I'm going to close this issue.
