### ISSUE TITLE
Audit the state of the current chef.sh docs and create tickets for the docs team

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#715]
The docs team has requested that we create issue for anything that needs updating on the site so they can work it. We'll want to set aside some time to read the site and cut issues for everything that needs cleanup.

**Comment by afiune** [comment]
We need to contact the Docs Team for more information but I have marked this issue
as a medium priority since we need to work on docs sooner rather than later.

**Comment by tas50** [comment]
Docs were all merged into a single source of truth.
