### ISSUE TITLE
[chef-analyze] Create an experimental release notes

### ISSUE THREAD

**Issue by afiune** [chef/chef-workstation#795]
Create experimental release notes for [chef-analyze](https://github.com/chef/chef-analyze). This could be done
in the repo wiki that can be copy and pasted when we do the official release.

## Acceptance criteria
Document the release notes for chef-analyze.

Aha! Link: https://chef.aha.io/features/SH-1747

**Comment by kagarmoe** [comment]
We have workstation release notes. Does it include chef-analyze? We (Docs) would prefer that it does, so we can keep release notes mayhem low.
