### ISSUE TITLE
Workstation should create .chef dirs in the user home by default

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#810]
After installing workstation every user needs a .chef dir, but we don't create it for them. If there isn't a .chef dir in the home dir then we should create it.

**Comment by tyler-ball** [comment]
Lets go ahead and fix this bug - we know it causes issues for users.

From a product view, we need an epic of "Configure all Chef Workstation products using a unified configuration approach". One question we need to explore there is: how do we configure CW in a system native way? For MacOS we probably need to be writing configuration into `/Library/Application Support/` or `~/Library/Application Support/`.
