### ISSUE TITLE
Workstation should launch the Chef app after installing it

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#819]
Right now after installing the app we don't launch it. Even if we don't set it to run at boot we should launch post-install.

**Comment by afiune** [comment]
# Done Done Done!!! 🎉 

![tenor-256512401](https://user-images.githubusercontent.com/5712253/73893725-afea7200-4837-11ea-8e18-24d1076e3876.gif)


This is also covering the work to launch the app at boot for macOS systems!
