### ISSUE TITLE
Running "chef push mygroup Policyfile.lock.json" throwing error CachedCookbookNotFound

### ISSUE THREAD

**Issue by MrCyrus** [chef/chef-workstation#843]
## Description

I've a policy cookbook with a pre-generated Policyfile.lock.json which I would like to 'push' to the Chef Server to a different policy group. So "copy" a POLICY_FILE from one POLICY_GROUP to another, but it is throwing an error ChefCLI::CachedCookbookNotFound complaining about not having the 'cache' files for referenced cookbooks.

## Details:
We've 3 POLICY_GROUPs:
   - sandbox
   - dev-test
   - production

and I need a way to "copy" a POLICY_FILE from one POLICY_GROUP to another. I've stored the policy cookbook in S3 for each of the POLICY_GROUPs so each POLICY_FILE  is in S3 3 times once for each POLICY_GROUP. I was expecting to be able to copy from S3 the POLICY_FILE from 'sandbox' (containing the Policyfile.lock.json used in 'sandbox')  and then run: 
```
chef push dev-test Policyfile.lock.json
```
to "copy" to 'dev-test', but since this is all running via Jenkins pipelines, the cached dependent cookbooks are NOT found in /home/jenkins/.chef-workstation/cache/cookbooks. I'm not seeing why the cached dependent cookbooks are required since I've already got a pre-generated Policyfile.lock.json with ALL needed info in it. If I only had Policyfile.rb, then yes cached cookbooks would be needed, but with an already generated Policyfile.lock.json with ALL dependencies defined it it, there is no need to look at any other cookbooks cached information.

I'm not seeing a 'force' option to force 'chef' to push a Policyfile.lock.json

## Chef Workstation Version

Chef Workstation version: 0.13.35
Chef Infra Client version: 15.6.10
Chef InSpec version: 4.18.39
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.16.11

## Platform Version

Ubuntu 18.04.3 LTS

**Comment by afiune** [comment]
@MrCyrus Thank you for creating this issue, we need to do a little more investigation using the workflow you have explained, we will get back to you with more valuable information.
