### ISSUE TITLE
Ship knife-ec2 1.0.32 in Workstation

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#981]
## Description
This includes a critical regression fix for AWS profiles not loading properly in knife-ec2 that needs to be pushed.

https://github.com/chef/knife-ec2/blob/master/CHANGELOG.md

## Chef Workstation Version
0.16

## Platform Version
N/A

**Comment by btm** [comment]
it looks like 1.0.32 was pulled in a while ago in 61ef2c7d445a01dbebf358314240291c528aee8f, yes? So it would be in Wednesday's 0.17 release tracked in #1023, yeah?

**Comment by tas50** [comment]
Yep this is in a current build now so this can get closed.
