### ISSUE TITLE
Fix the update_dep.sh script to properly fire

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#982]
## Description
This script fires in DK, but not in Workstation. 

logs.cd.chef.co/raw/chef-chef-workstation-master-ruby_gem_published-knife-ec2-1-0-32

## Chef Workstation Version
Master

## Platform Version
N/A

**Comment by jonsmorrow** [comment]
https://app.zenhub.com/workspaces/chef-workstation-5c0aced04b5806bc2bfb9347/issues/chef/chef-workstation/986
